# lovelace_gen

title: Anwesenheit

views:
  - title: Personen
    path: presence
    icon: mdi:account-multiple
    type: custom:horizontal-layout
    layout:
      max_cols: 2
    cards:
      - type: entities  
        entities:
          - entity: person.wolfgang
          - entity: person.christina
          - type: custom:fold-entity-row
            head:
              type: section
              label: Automation
            padding: 5
            entities:
              - entity: automation.abwesenheitsschaltung
                icon: mdi:account-off
                tap_action: 
                  action: toggle
              - entity: automation.anwesenheitsschaltung
                icon: mdi:account-outline
                tap_action: 
                  action: toggle
          - type: custom:fold-entity-row
            head:
              type: section
              label: Sonos Automation
            padding: 5
            entities:
              - entity: automation.sonos_starten
                icon: mdi:music
                tap_action: 
                  action: toggle
              - entity: automation.sonos_stoppen
                icon: mdi:music-off
                tap_action: 
                  action: toggle
      - type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.fenster_turkontaktsensor
            name: Wohnungstür
            icon: mdi:door
            secondary_info: last-changed
          - entity: binary_sensor.bewegungsmelder
            secondary_info: last-changed
          - entity: binary_sensor.tradfri_bewegungsmelder
            secondary_info: last-changed
          - type: custom:fold-entity-row
            head:
              type: section
              label: Alarm
            padding: 5
            entities:
              - entity: automation.bewegungsmelder_alarm
                name: Bewegungsmelder Alarm
                tap_action: 
                  action: toggle
              - entity: script.xiaomi_gateway_alarm_stop
                name: Alarm ausschalten
                icon: mdi:volume-off
                tap_action: 
                  action: toggle
          - type: custom:fold-entity-row
            head:
              type: section
              label: Benachrichtigungen
            padding: 5
            entities:
              - entity: automation.benachrichtigung_bewegung_erkannt
                name: Bewegung erkannt
                icon: mdi:cellphone-message
                tap_action: 
                  action: toggle
              - entity: automation.benachrichtigung_wohnungstur_offen
                name: Wohnungstür offen
                icon: mdi:cellphone-message
                tap_action: 
                  action: toggle
      - type: entities
        entities:
          - entity: automation.licht_bewegung_kuche
            type: custom:multiple-entity-row
            entities:
              - entity: sensor.bewegungsmelder
                name: Helligkeit
            toggle: true
            icon: mdi:motion-sensor
            name: Lichtsteuerung Küche
            tap_action:
              action: toggle
            double_tap_action:
              action: navigate
              navigation_path: /config/automation/edit/1629983354095
          - entity: automation.licht_bewegung_flur
            type: custom:multiple-entity-row
            entities:
              - entity: sensor.illumination_7811dcb258d1
                name: Helligkeit
            toggle: true
            icon: mdi:motion-sensor
            name: Lichtsteuerung Flur
            tap_action:
              action: toggle
            double_tap_action:
              action: navigate
              navigation_path: /config/automation/edit/1629983281720
      # - type: entities
      #   entities:
      #     - entity: switch.on_off_plug_in_unit_12
      #       name: Kamera
      #       icon: mdi:cctv
      # - type: conditional
      #   conditions:
      #     - entity: switch.on_off_plug_in_unit_12
      #       state: "on"
      #   card:
      #     type: picture-entity
      #     entity: camera.ffmpeg
      #     camera_view: live
      #     show_name: false
      #     show_state: false
  - title: Karte
    path: map
    icon: mdi:map
    panel: true
    cards:
      - type: map
        default_zoom: 15
        entities:
          - entity: device_tracker.iphone11pro_2
          - zone.home
          - zone.agcs
          - zone.christina
          - zone.eltern