# lovelace_gen

title: Anwesenheit

views:
  - title: Personen
    path: presence
    icon: mdi:account-multiple
    cards:
      - type: entities  
        entities:
          - entity: person.wolfgang
            secondary_info: last-changed
            tap_action: 
              action: none
          - type: custom:fold-entity-row
            head:
              type: section
              label: Automation
            padding: 5
            entities:
              - entity: automation.abwesenheitsschaltung
                icon: mdi:account-off
                tap_action: 
                  action: toggle
              - entity: automation.anwesenheitsschaltung
                icon: mdi:account-outline
                tap_action: 
                  action: toggle
          - type: custom:fold-entity-row
            head:
              type: section
              label: Sonos Automation
            padding: 5
            entities:
              - entity: automation.sonos_starten
                icon: mdi:music
                tap_action: 
                  action: toggle
              - entity: automation.sonos_stoppen
                icon: mdi:music-off
                tap_action: 
                  action: toggle
      - type: conditional
        conditions:
          - entity: device_tracker.hikam_4452
            state: "home"
        card:
          type: picture-entity
          entity: camera.ffmpeg
          title: Kamera
      - type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.fenster_turkontaktsensor
            name: Wohnungstür
            icon: mdi:door
            secondary_info: last-changed
          - entity: binary_sensor.bewegungsmelder
            secondary_info: last-changed
          - type: custom:fold-entity-row
            head:
              type: section
              label: Alarm
            padding: 5
            entities:
              - entity: automation.bewegungsmelder_alarm
                tap_action: 
                  action: toggle
              - entity: script.xiaomi_gateway_alarm_stop
                name: Alarm ausschalten
                icon: mdi:volume-off
                tap_action: 
                  action: toggle
          - type: custom:fold-entity-row
            head:
              type: section
              label: Benachrichtigungen
            padding: 5
            entities:
              - entity: automation.benachrichtigung_bewegung_erkannt
                name: Bewegung erkannt
                icon: mdi:cellphone-message
                tap_action: 
                  action: toggle
              - entity: automation.benachrichtigung_wohnungstur_offen
                name: Wohnungstür offen
                icon: mdi:cellphone-message
                tap_action: 
                  action: toggle
  - title: Karte
    path: map
    icon: mdi:map
    panel: true
    cards:
      - type: map
        default_zoom: 15
        entities:
          - entity: device_tracker.iphone11pro_2
          - entity: device_tracker.x1_sdrive18i
          - zone.home
          - zone.agcs
          - zone.christina
          - zone.eltern