# lovelace_gen

title: System

views:
  - title: System
    visible:
      - user: b6464705fc4e405abce8058610b4bcc7
    path: system
    icon: mdi:settings-outline
    # panel: true
    # cards:
    #   - type: custom:layout-card
    #     max_columns: 2
    cards:
      - type: entities
        entities:
          - type: 'custom:paper-buttons-row'
            buttons:
              - entity: script.1570443737111
                name: Mitteilung löschen
                style:
                  text:  
                    color: var(--primary-text-color)
              - entity: script.1570439203461
                name: Badge löschen
                style:
                  text:  
                    color: var(--primary-text-color)
      - type: entities  
        entities:
          - entity: switch.pi_hole
            icon: mdi:pi-hole
            tap_action: 
              action: call-service
              service: browser_mod.popup
              service_data:
                deviceID: this
                title: PI-Hole Stats
                card:
                  type: custom:auto-entities
                  card:
                    type: entities 
                  filter:
                      include:
                        - entity_id: "sensor.pi_hole_*"      
      - type: entities
        entities:
          - entity: automation.battery_persistent_notification
            tap_action: 
              action: call-service
              service: browser_mod.popup
              service_data:
                deviceID: this
                title: Batteriestatus
                card:
                  type: custom:auto-entities
                  card:
                    type: entities 
                  filter:
                    include:
                      - entity_id: "sensor.*_battery_level"
                        options:
                          type: custom:battery-entity-row
                    exclude:
                      - entity_id: "*iphone*"
                      - entity_id: "*ipad*"
          - type: custom:fold-entity-row
            head:
              type: section
              label: Einstellungen
            padding: 5
            entities:
              - entity: input_number.battery_alert
                name: Grenzwert
                tap_action: 
                  action: none
              - entity: script.battery_persistent_notification_clear
                tap_action: 
                  action: toggle
      - type: glance
        columns: 4
        show_name: false
        entities:
          - entity: sensor.memory_use_percent
            name: Memory
          - entity: sensor.memory_use
            name: Memory
          - entity: sensor.disk_use_percent
            name: Disk
          - entity: sensor.disk_use
            name: Disk
          - entity: sensor.swap_use_percent
            name: Swap
            icon: mdi:harddisk-plus
          - entity: sensor.processor_use
            name: CPU
            icon: mdi:chip
          - entity: sensor.cpu_temperature
            name: CPU Temp
            icon: mdi:thermometer
          - entity: sensor.online_time
            name: Zeit
      - type: glance
        columns: 4
        show_name: false
        entities:
          - sensor.net_download_max
          - sensor.net_download_cur
          - sensor.fritz_netmonitor
          - sensor.net_uptime
          - sensor.net_upload_max
          - sensor.net_upload_cur
          - entity: sensor.wireguard_iphonepro
            icon: mdi:cellphone-iphone
          - entity: sensor.wireguard_ipad
            icon: mdi:tablet-ipad
      - type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.updater
            name: HA Updates
            type: custom:multiple-entity-row
            secondary_info:
              attribute: newest_version
            tap_action: 
              action: call-service
              service: browser_mod.navigate
              service_data: 
                navigation_path: /hassio
                deviceID: this
          - entity: sensor.hacs
            name: Hacs Updates
            tap_action: 
              action: call-service
              service: browser_mod.navigate
              service_data: 
                navigation_path: /hacs
                deviceID: this
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.samba_backup
            icon: mdi:content-save-all
            type: custom:multiple-entity-row
            secondary_info:
              attribute: last_backup
            tap_action: 
              action: call-service
              service: browser_mod.popup
              service_data:
                deviceID: this
                title: Status
                card:
                  type: entities
                  entities:
                    - attribute: backups_local
                      entity: sensor.samba_backup
                      icon: 'mdi:file-outline'
                      name: Local Backups
                      type: attribute
                    - attribute: backups_remote
                      entity: sensor.samba_backup
                      icon: 'mdi:file-move-outline'
                      name: Remote Backups
                      type: attribute
                    - attribute: total_backups_succeeded
                      entity: sensor.samba_backup
                      icon: 'mdi:file-check-outline'
                      name: Succeded Backups
                      type: attribute
                    - attribute: total_backups_failed
                      entity: sensor.samba_backup
                      icon: 'mdi:file-cancel-outline'
                      name: Failed Backups
                      type: attribute
                    - attribute: last_backup
                      entity: sensor.samba_backup
                      icon: 'mdi:file-clock-outline'
                      name: Last Backup
                      type: attribute
          # - entity: automation.tagliches_backup_auto_backup
          #   icon: mdi:content-save-all
          #   tap_action: 
          #     action: toggle
          # - sensor.auto_backup      
      - type: entities
        entities:
          - type: weblink
            url: /map  
            name: Karte 
            icon: mdi:map-outline          