# lovelace_gen

#### popup instead of more-info
popup_cards:
  sensor.samba_backup:
    title: Status
    card:
      type: entities
      entities:
        - attribute: backups_local
          entity: sensor.samba_backup
          icon: 'mdi:file-outline'
          name: Local Backups
          type: attribute
        - attribute: backups_remote
          entity: sensor.samba_backup
          icon: 'mdi:file-move-outline'
          name: Remote Backups
          type: attribute
        - attribute: total_backups_succeeded
          entity: sensor.samba_backup
          icon: 'mdi:file-check-outline'
          name: Succeded Backups
          type: attribute
        - attribute: total_backups_failed
          entity: sensor.samba_backup
          icon: 'mdi:file-cancel-outline'
          name: Failed Backups
          type: attribute
        - attribute: last_backup
          entity: sensor.samba_backup
          icon: 'mdi:file-clock-outline'
          name: Last Backup
          type: attribute

  automation.batterie_benachrichtigung:
    title: Batteriestatus
    card:
      type: custom:auto-entities
      card:
        type: entities 
      filter:
        include:
          - entity_id: "sensor.*_battery_level"
            options:
              type: custom:battery-entity-row
        exclude:
          - entity_id: "*iphone*"
          - entity_id: "*ipad*"

  switch.pi_hole:
    title: PI-Hole Stats
    card:
      type: custom:auto-entities
      card:
        type: entities 
      filter:
          include:
            - entity_id: "sensor.pi_hole_*"  
#### #### #### #### #### #### #### #### #### #### 

title: System

views:
  - title: System
    path: system
    icon: mdi:settings-outline
    cards:
      - type: entities
        entities:
          - type: 'custom:paper-buttons-row'
            buttons:
              - entity: script.notify_clean_messages
                name: Mitteilung löschen
                style:
                  text:  
                    color: var(--primary-text-color)
              - entity: script.notify_clean_badge
                name: Badge löschen
                style:
                  text:  
                    color: var(--primary-text-color)
      - type: entities  
        entities:
          - entity: switch.pi_hole
            icon: mdi:pi-hole    
      - type: entities
        entities:
          - entity: automation.batterie_benachrichtigung
          - type: custom:fold-entity-row
            head:
              type: section
              label: Einstellungen
            padding: 5
            entities:
              - entity: input_number.battery_alert
                name: Grenzwert
                tap_action: 
                  action: none
              - entity: script.battery_persistent_notification_clear
                tap_action: 
                  action: toggle
      - type: glance
        columns: 5
        show_name: false
        entities:
          - entity: sensor.processor_use
            name: CPU   
            style: |
                :host {
                  color: 
                  {% if (states.sensor.processor_use.state | int) > 30 %}
                    red
                  {% endif %}
                  ;
                }     
          - entity: sensor.cpu_temperature
            icon: mdi:thermometer
            name: CPU Temp
            style: |
                :host {
                  color: 
                  {% if (states.sensor.cpu_temperature.state | int) > 70 %}
                    red
                  {% endif %}
                  ;
                }
          - entity: sensor.memory_use_percent
            name: Memory 
          - entity: sensor.swap_use_percent
            name: Swap
            icon: mdi:file-swap         
          - entity: sensor.disk_use_percent
            name: Disk                
      - type: entities
        show_header_toggle: false
        entities:
          - entity:  sensor.updater_core
            type: custom:multiple-entity-row
            name: Core
            show_state: false
            icon: mdi:update
            entities:
              - attribute: current_version
                name: Installiert
              - attribute: newest_version
                name: Verfügbar
            tap_action: 
              action: fire-dom-event
              browser_mod:
                command: navigate
                navigation_path: /hassio
          - entity:  sensor.updater_supervisor
            type: custom:multiple-entity-row
            name: Supervisor
            icon: mdi:update
            show_state: false
            entities:
              - attribute: current_version
                name: Installiert
              - attribute: newest_version
                name: Verfügbar
            tap_action: 
              action: fire-dom-event
              browser_mod:
                command: navigate
                navigation_path: /hassio
          - entity:  sensor.updater_supervisor
            type: custom:multiple-entity-row
            name: Add-ons
            icon: mdi:update
            tap_action: 
              action: fire-dom-event
              browser_mod:
                command: navigate
                navigation_path: /hassio
          - entity: sensor.hacs
            name: Hacs
            tap_action: 
              action: fire-dom-event
              browser_mod:
                command: navigate 
                navigation_path: /hacs
          - type: custom:fold-entity-row
            padding: 5
            head:
              type: section
              label: Details
            entities:
              - entity: sensor.online_time
                name: Hass online
                icon: mdi:home-assistant
              - entity: sensor.last_boot
                name: Raspi online
                icon: mdi:raspberry-pi
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.samba_backup
            icon: mdi:content-save-all
            type: custom:multiple-entity-row
            secondary_info:
              attribute: last_backup
      - type: glance
        columns: 5
        show_name: false
        entities:
          - entity: sensor.net_download_max
            icon: mdi:cloud-download
          - entity: sensor.net_upload_max
            icon: mdi:cloud-upload
          - entity: sensor.net_download_cur
            icon: mdi:cloud-download-outline
          - entity: sensor.net_upload_cur
            icon: mdi:cloud-upload-outline
          - sensor.fritz_netmonitor
          - sensor.net_uptime
          - entity: sensor.wireguard_iphonepro
            icon: mdi:cellphone-iphone
          - entity: sensor.wireguard_ipad
            icon: mdi:tablet-ipad                    
 