# lovelace_gen

button_card_templates: !include includes/button_card_templates.yaml
popup_cards: !include includes/popups/popup_cards.yaml

title: System

views:
  - !include views_system/system.yaml
  - !include views_system/automations.yaml
  - !include views_system/fritz.yaml
  - !include views_system/links.yaml