DOMAIN = "custom_update_entities"
CONF_UPDATERS = "updaters"
CONF_NAME = "name"
CONF_LATEST_VERSION_ENTITY = "latest_version_entity"
CONF_INSTALLED_VERSION_ENTITY = "installed_version_entity"
CONF_UPDATE_ACTION = "update_action"
CONF_RELEASE_NOTES_URL = "release_notes_url"
CONF_LOGO_URL = "logo_url"
