homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

config:
map:
mobile_app:
person:
ssdp:
sun:
system_health:
api:
zeroconf:
updater:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

frontend:
  themes: !include_dir_merge_named themes

lovelace_gen:

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards: !include lovelace/dashboards.yaml
    
logger:
  default: info
  # logs:
  #   hacs: debug
   
history: !include config_files/history/history.yaml
recorder: !include config_files/history/recorder.yaml
influxdb: !include config_files/history/influxdb.yaml

logbook:
  exclude:
    domains:
      - group
      - calendar

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml

alexa: !include config_files/alexa.yaml
switch: !include config_files/switch.yaml  
light: !include config_files/light.yaml
input_select: !include config_files/input_selects.yaml
input_boolean: !include config_files/input_boolean.yaml
input_datetime: !include config_files/input_datetime.yaml
input_number: !include config_files/input_number.yaml
counter: !include config_files/counter.yaml
media_player: !include config_files/media_player.yaml
ios: !include config_files/ios.yaml
homekit: !include config_files/homekit.yaml
browser_mod: !include config_files/browser_mod.yaml
device_tracker: !include config_files/device_tracker.yaml
camera: !include config_files/camera.yaml
sensor: !include_dir_merge_list config_files/sensors/
template:  !include_dir_merge_list config_files/template/
binary_sensor: !include_dir_merge_list config_files/binary_sensors/
timer:
input_text:

python_script:

stream:

ffmpeg: