homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
config:
map:
mobile_app:
person:
ssdp:
sun:
system_health:
api:
zeroconf:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

frontend:
  themes: !include_dir_merge_named themes

lovelace_gen:

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards: !include lovelace/dashboards.yaml
    
logger:
  default: info
  # logs:
  #   hacs: debug
  
updater:
  
history: !include config_files/history/history.yaml
recorder: !include config_files/history/recorder.yaml

logbook:
  exclude:
    domains:
      - group
      - calendar

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml

alexa: !include config_files/alexa.yaml
switch: !include config_files/switch.yaml  
light: !include config_files/light.yaml
input_select: !include config_files/input_selects.yaml
input_boolean: !include config_files/input_boolean.yaml
input_datetime: !include config_files/input_datetime.yaml
input_number: !include config_files/input_number.yaml
counter: !include config_files/counter.yaml
media_player: !include config_files/media_player.yaml
influxdb: !include config_files/influxdb.yaml
ios: !include config_files/ios.yaml
homekit: !include config_files/homekit.yaml
browser_mod: !include config_files/browser_mod.yaml

sensor: !include_dir_merge_list config_files/sensors/
binary_sensor: !include_dir_merge_list config_files/binary_sensors/

python_script:

device_tracker:
  - platform: iphonedetect
    consider_home: 60
    scan_interval: 12
    new_device_defaults:
      track_new_devices: true
    hosts:
      iphone_wolfgang: 192.168.200.22
      iphone_christina: 192.168.200.35

camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.200.29
    token: !secret xiaomi_vacuum
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    auto_update: false
    attributes:
      - calibration_points
    # colors:
    #   color_map_outside: [3, 169, 244]
    map_transformation:
      trim:
        top: 10
        bottom: 10
        left: 10
        right: 10 