homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
config:
map:
map:
mobile_app:
person:
ssdp:
sun:
system_health:
api:
zeroconf:

http:
  base_url: !secret hass_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

logger:
  default: info
  
updater:
  include_used_components: true
  
# history:
#   exclude:
#     domains:
#       - group
#       - calendar
#     entities:
#       - automation.dismiss_annoying_notification

logbook:
  exclude:
    domains:
      - group
      - calendar
    entities:
      - automation.dismiss_annoying_notification

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml

recorder: !include configs/recorder.yaml
alexa: !include configs/alexa.yaml
switch: !include configs/switch.yaml  
light: !include configs/light.yaml
input_select: !include configs/input_selects.yaml
input_boolean: !include configs/input_boolean.yaml
input_datetime: !include configs/input_datetime.yaml
input_number: !include configs/input_number.yaml
counter: !include configs/counter.yaml
media_player: !include configs/media_player.yaml
influxdb: !include configs/influxdb.yaml
ios: !include configs/push.yaml
homekit: !include configs/homekit.yaml
browser_mod: !include configs/browser_mod.yaml
calendar: !include configs/calendar.yaml
homematic: !include configs/homematic.yaml

sensor: !include_dir_merge_list configs/sensors/

# hue:
#   bridges:
#     - host: 192.168.200.52
#       allow_unreachable: true
#       allow_hue_groups: false

vacuum:
  - platform: xiaomi_miio
    host: 192.168.200.28
    token: !secret xiaomi_vacuum

device_tracker:
  - platform: fritz
    host: 192.168.200.1
    consider_home: 600

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway

remote:
  - platform: harmony
    name: harmony_hub
    host: 192.168.200.55

weather:
  - platform: darksky
    api_key: !secret dark_syk

yeelight:
  devices:
    192.168.200.59:
      name: Nachttischlampe Wolfgang
    192.168.200.42:
      name: Nachttischlampe Anita

bmw_connected_drive:
  x1:
    username: !secret bmw_user
    password: !secret bmw_password
    region: "rest_of_world"

camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.200.40:554/onvif1

clean_up_snapshots_service:
  host: !secret hass_url
  token: !secret snapshot_token
  number_of_snapshots_to_keep: 6

zone:
  - name: Arbeit
    latitude: 48.104569
    longitude: 11.645074
    radius: 100
    icon: mdi:office-building

auto_backup:
  auto_purge: true
  backup_timeout: 4800

fritzbox:
  devices:
    - host: fritz.box
      username: !secret fritz_user
      password: !secret fritz_password

python_script:

tplink:

stream:

ffmpeg:
