homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

config:
map:
mobile_app:
person:
ssdp:
sun:
system_health:
api:
zeroconf:
stream:
diagnostics:
my:
# conversation:
homeassistant_alerts:

http:
  server_port: 8124
  use_x_forwarded_for: true
  # trusted_proxies:
  #   - 172.30.33.0/24
  trusted_proxies:
    - 127.0.0.1
    - 172.30.33.0/24
    - 192.168.200.33
    - 172.17.0.6
    - 172.17.0.0/24

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: /hacsfiles/lovelace-card-mod/card-mod.js
  
lovelace_gen:

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards: !include lovelace/dashboards.yaml
    
logger:
  default: info
  filters:
    homeassistant.components.rest.data:
      - "Error fetching data:*"
    homeassistant.components.rest.sensor:
      - "Empty reply found when expecting JSON data"
    custom_components.monitor_docker.helpers:
      - ": *Container not available anymore*"
   
history: #!include config_files/history/history.yaml
recorder: !include config_files/history/recorder.yaml
influxdb: !include config_files/history/influxdb.yaml

logbook:
  exclude:
    domains:
      - group
      - calendar

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml

switch: !include config_files/switch.yaml  
light: !include config_files/light.yaml
input_select: !include config_files/input_selects.yaml
input_boolean: !include config_files/input_boolean.yaml
input_datetime: !include config_files/input_datetime.yaml
input_number: !include config_files/input_number.yaml
counter: !include config_files/counter.yaml
media_player: !include config_files/media_player.yaml
ios: !include config_files/ios.yaml
homekit: !include config_files/homekit.yaml
device_tracker: !include config_files/device_tracker.yaml
# camera: !include config_files/camera.yaml
sensor: !include_dir_merge_list config_files/sensors/
template:  !include_dir_merge_list config_files/template/
binary_sensor: !include_dir_merge_list config_files/binary_sensors/
timer:
input_text:
input_button:
schedule:

python_script:

# ffmpeg:

wake_on_lan:

shell_command:
  ds118_shutdown: bash /config/scripts/ds118_shutdown.sh
  ds118_surveillance_start: bash /config/scripts/ds118_surveillance_start.sh
  ds118_surveillance_stop: bash /config/scripts/ds118_surveillance_stop.sh

home_connect_alt:
  client_id: !secret client_id
  client_secret: !secret client_secret
  name_template: $brand $appliance - $name
  language: de 
  sensor_value_translation: <server | local> 

notify:  
  - name: all_ios_devices
    platform: group
    services:
      - service: mobile_app_iphone14pro

monitor_docker: !include config_files/monitor_docker.yaml

custom_update_entities:
  updaters:
    - name: Nextcloud Hub
      latest_version_entity: sensor.nextcloud_latest_version
      installed_version_entity: sensor.nextcloud_version
      update_action:
        - service: browser_mod.navigate
          data:
            path: https://next.tanzer-cloud.de

emulated_hue:
  expose_by_default: false
  entities:
    light.flur:
      hidden: false
    light.kuche:
      hidden: false
    light.wohnzimmer_decke:
      hidden: false
    light.schlafzimmer:
      hidden: false
    switch.steckdose_1:
      hidden: false
    switch.steckdose_2:
      hidden: false
    switch.steckdose_3:
      hidden: false
    switch.steckdosenleiste:
      hidden: false