homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
  # internal_url: !secret internal_url
  # external_url: !secret hass_url

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
config:
# map:
mobile_app:
person:
ssdp:
sun:
system_health:
api:
zeroconf:

http:
  # base_url: !secret hass_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.4
    - 172.30.33.3
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

lovelace_gen:

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards:
    lovelace-system:
      mode: yaml
      title: System
      icon: mdi:tune
      show_in_sidebar: true
      filename: ui-system.yaml
      require_admin: true
    lovelace-map:
      mode: yaml
      title: Map
      icon: mdi:map-outline
      show_in_sidebar: false
      filename: ui-map.yaml
      require_admin: true
    lovelace-presence:
      mode: yaml
      title: Presence
      icon: mdi:account-multiple
      show_in_sidebar: true
      filename: ui-presence.yaml
      require_admin: true
    lovelace-car:
      mode: yaml
      title: Auto
      icon: mdi:car-hatchback
      show_in_sidebar: true
      filename: ui-car.yaml
      require_admin: true

logger:
  default: info
  # logs:
  #   hacs: debug
  
updater:
  include_used_components: true
  
# history:
#   exclude:
#     domains:
#       - group
#       - calendar
#     entities:
#       - automation.dismiss_annoying_notification

logbook:
  exclude:
    domains:
      - group
      - calendar
    entities:
      - automation.dismiss_annoying_notification

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml

recorder: !include config_files/recorder.yaml
alexa: !include config_files/alexa.yaml
switch: !include config_files/switch.yaml  
light: !include config_files/light.yaml
input_select: !include config_files/input_selects.yaml
input_boolean: !include config_files/input_boolean.yaml
input_datetime: !include config_files/input_datetime.yaml
input_number: !include config_files/input_number.yaml
counter: !include config_files/counter.yaml
media_player: !include config_files/media_player.yaml
influxdb: !include config_files/influxdb.yaml
ios: !include config_files/push.yaml
homekit: !include config_files/homekit.yaml
browser_mod: !include config_files/browser_mod.yaml
# calendar: !include config_files/calendar.yaml
#homematic: !include config_files/homematic.yaml

sensor: !include_dir_merge_list config_files/sensors/

vacuum:
  - platform: xiaomi_miio
    host: 192.168.200.28
    token: !secret xiaomi_vacuum

device_tracker:
  - platform: fritz
    host: 192.168.200.1
    # consider_home: 600

# xiaomi_aqara:
#   discovery_retry: 5
#   gateways:
#     - key: !secret xiaomi_gateway

# remote:
#   - platform: harmony
#     name: harmony_hub
#     host: 192.168.200.55

weather:
  - platform: darksky
    api_key: !secret dark_syk

yeelight:
  devices:
    192.168.200.59:
      name: Nachttischlampe Wolfgang

bmw_connected_drive:
  x1:
    username: !secret bmw_user
    password: !secret bmw_password
    region: "rest_of_world"

camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.200.40:554/onvif1

auto_backup:
  auto_purge: true
  backup_timeout: 4800

python_script:

tplink:

stream:

ffmpeg:

#switches for addons
hassio_info:

shell_command:
  restart_ds118: /config/scripts/shutdown_ds118.sh
  backup_raspi: /config/scripts/backup.sh