- platform: fritzbox_netmonitor
  host: 192.168.200.1

- platform: huesensor

- platform: systemmonitor
  resources:
      - type: memory_free
      - type: memory_use
      - type: memory_use_percent
      - type: processor_use
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: load_1m 
      - type: load_5m
      - type: load_15m

- platform: template
  sensors:
      valve_bed_room:
        entity_id: climate.oeq1696369
        friendly_name: "Schlafzimmer Ventil"
        unit_of_measurement: "%"
        value_template: '{{ states.climate.oeq1696369.attributes.valve }}'
      valve_office:
        entity_id: climate.oeq1714751
        friendly_name: "Büro Ventil"
        unit_of_measurement: "%"
        value_template: '{{ states.climate.oeq1714751.attributes.valve }}'
      valve_living_room:
        entity_id: climate.oeq1696358
        friendly_name: "Wohnzimmer Ventil"
        unit_of_measurement: "%"
        value_template: '{{ states.climate.oeq1696358.attributes.valve }}'
      valve_bath:
        entity_id: climate.oeq1701003
        friendly_name: "Bad Ventil"
        unit_of_measurement: "%"
        value_template: '{{ states.climate.oeq1701003.attributes.valve }}'
      battery_radiator_office_1:
        entity_id: climate.oeq1667238
        friendly_name: "Batterie Thermostat Büro"
        value_template: '{{ states.climate.oeq1667238.attributes.battery }}'
      battery_radiator_office_2:
        entity_id: climate.oeq1714751
        friendly_name: "Batterie Heizung Büro"
        value_template: '{{ states.climate.oeq1714751.attributes.battery }}'
      battery_radiator_bedroom:
        entity_id: climate.oeq1696369
        friendly_name: "Batterie Heizung Schlafzimmer"
        value_template: '{{ states.climate.oeq1696369.attributes.battery }}'
      battery_radiator_livingroom:
        entity_id: climate.oeq1696358
        friendly_name: "Batterie Heizung Wohnzimmer"
        value_template: '{{ states.climate.oeq1696358.attributes.battery }}'
      battery_radiator_bath:
        entity_id: climate.oeq1701003
        friendly_name: "Batterie Heizung Bad"
        value_template: '{{ states.climate.oeq1701003.attributes.battery }}'
      battery_sensor_bedroom:
        entity_id: sensor.humidity_158d0001b8c96c
        device_class: battery
        friendly_name: "Batterie Sensor Schlafzimmer"
        value_template: '{{ states.sensor.humidity_158d0001b8c96c.attributes.battery_level }}'
      battery_sensor_livingroom:
        entity_id: sensor.humidity_158d0001b8c998
        device_class: battery
        friendly_name: "Batterie Sensor Wohnzimmer"
        value_template: '{{ states.sensor.humidity_158d0001b8c998.attributes.battery_level }}'
      battery_sensor_kitchen:
        entity_id: sensor.humidity_158d0001b8c998
        device_class: battery
        friendly_name: "Batterie Sensor Küche"
        value_template: '{{ states.sensor.humidity_158d0001b8c998.attributes.battery_level }}'
      battery_sensor_bath:
        entity_id: sensor.humidity_158d00023258bd
        device_class: battery
        friendly_name: "Batterie Sensor Bad"
        value_template: '{{ states.sensor.humidity_158d00023258bd.attributes.battery_level }}'
      battery_sensor_motion:
        entity_id: binary_sensor.motion_sensor_158d00023e77cb
        device_class: battery
        friendly_name: "Batterie Sensor Motion"
        value_template: '{{ states.binary_sensor.motion_sensor_158d00023e77cb.attributes.battery_level }}'
      battery_sensor_door:
        entity_id: binary_sensor.door_window_sensor_158d00022f13a0
        device_class: battery
        friendly_name: "Batterie Sensor Motion Door/Window"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d00022f13a0.attributes.battery_level }}'
      battery_sensor_button_1:
        entity_id: binary_sensor.switch_158d0002131462
        device_class: battery
        friendly_name: "Batterie Sensor Button 1"
        value_template: '{{ states.binary_sensor.switch_158d0002131462.attributes.battery_level }}'
      battery_sensor_button_2:
        entity_id: binary_sensor.switch_158d000213621b
        device_class: battery
        friendly_name: "Batterie Sensor Button 2"
        value_template: '{{ states.binary_sensor.switch_158d000213621b.attributes.battery_level }}'
      battery_sensor_wall_switch:
        entity_id: binary_sensor.wall_switch_158d00025303aa
        device_class: battery
        friendly_name: "Batterie Sensor Wall Switch"
        value_template: '{{ states.binary_sensor.wall_switch_158d00025303aa.attributes.battery_level }}'      
      battery_sensor_wall_switch_double:
        entity_id: binary_sensor.wall_switch_both_158d000254275c
        device_class: battery
        friendly_name: "Batterie Sensor Wall Switch Double"
        value_template: '{{ states.binary_sensor.wall_switch_both_158d000254275c.attributes.battery_level }}'
      xiaomi_vacuum_status:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Status"
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}'
      xiaomi_vacuum_main_brush_left:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Main Brush"
        unit_of_measurement: 'h'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}'
      xiaomi_vacuum_side_brush_left:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Side Brush"
        unit_of_measurement: 'h'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}'
      xiaomi_vacuum_filter_left:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Filter"
        unit_of_measurement: 'h'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}'
      xiaomi_vacuum_sensor_dirty_left:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Sensor"
        unit_of_measurement: 'h'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }}'
      xiaomi_vacuum_sensor_battery:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Batterie"
        unit_of_measurement: '%'
        device_class: battery
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}'
        icon_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon }}'
      radiator_bed_room_keylock:
        entity_id: homematic.ccu2
        friendly_name: "Tastensperre Schlafzimmer"
        value_template: '{{ states.homematic.ccu2.attributes.block_bed_room }}'
      radiator_living_room_keylock:
        entity_id: homematic.ccu2
        friendly_name: "Tastensperre Wohnzimmer"
        value_template: '{{ states.homematic.ccu2.attributes.block_living_room	 }}'
      radiator_office_keylock:
        entity_id: homematic.ccu2
        friendly_name: "Tastensperre Büro"
        value_template: '{{ states.homematic.ccu2.attributes.block_office }}'
      radiator_bath_keylock:
        entity_id: homematic.ccu2
        friendly_name: "Tastensperre Bad"
        value_template: '{{ states.homematic.ccu2.attributes.block_bath }}'
      remote_state:
        entity_id: remote.harmony_hub
        friendly_name: "Multimedia"
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      presence:
        entity_id: person.anita, person.wolfgang
        friendly_name: Anwesenheit
        value_template: >
            {% if is_state('person.anita', 'home') or is_state('person.wolfgang', 'home')  %}
              home
            {% else %}
              not_home
            {% endif %}
      dark_sky_temperature:
        entity_id: weather.dark_sky
        friendly_name: Temperatur
        value_template: '{{ states.weather.dark_sky.attributes.temperature }}'
      hue_dimmer_battery_livingroom:
        entity_id: sensor.hue_dimmer_wohnzimmer
        friendly_name: Hue dimmer Wohnzimmer
        value_template: '{{ states.sensor.hue_dimmer_wohnzimmer.attributes.battery }}'
        device_class: battery
      hue_dimmer_battery_bedroom:
        entity_id: sensor.hue_dimmer_schlafzimmer
        friendly_name: Hue dimmer Schlafzimmer
        value_template: '{{ states.sensor.hue_dimmer_schlafzimmer.attributes.battery }}'
        device_class: battery
      car_days_in_use:
        entity_id: sensor.x1_sdrive18i_mileage
        friendly_name: Autonutzung in Tagen
        value_template: '{{ (as_timestamp(now()) - as_timestamp("2019-07-02 00:00:00") ) | timestamp_custom("%j")  | int }}'
        icon_template: mdi:calendar-month
      car_km_threshold:
        entity_id: sensor.x1_sdrive18i_mileage
        friendly_name: KM Schwelle
        value_template: '{{ ((as_timestamp(now()) - as_timestamp("2019-07-02 00:00:00") ) | timestamp_custom("%j")  | int) * 39 }} '
        unit_of_measurement: 'km'
        icon_template: mdi:card-bulleted-outline
      car_km_usage:
        entity_id: sensor.x1_sdrive18i_mileage
        friendly_name: KM Verbraucht (in %)
        value_template: '{{ ( (states ( "sensor.x1_sdrive18i_mileage" ) | int) / (states ( "sensor.car_km_threshold" ) | int) * 100 ) | round(2) }}'
        unit_of_measurement: '%'
        icon_template: mdi:car-cruise-control
      hs110_amps:
        friendly_name_template: "HS110 Aktuelle Stromstärke"
        value_template: '{{ states.switch.wifi_steckdose.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
        icon_template: mdi:clipboard-pulse-outline
      hs110_watts:
        friendly_name_template: "HS110 Aktuelle Leistung"
        value_template: '{{ states.switch.wifi_steckdose.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
        icon_template: mdi:clipboard-pulse-outline
      hs110_total_kwh:
        friendly_name_template: "HS110 Gesamtverbrauch"
        value_template: '{{ states.switch.wifi_steckdose.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
        icon_template: mdi:clipboard-pulse-outline
      hs110_volts:
        friendly_name_template: "HS110 Aktuelle Spannung"
        value_template: '{{ states.switch.wifi_steckdose.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
        icon_template: mdi:clipboard-pulse-outline
      hs110_today_kwh:
        friendly_name_template: "HS110 Tagesverbrauch"
        value_template: '{{ states.switch.wifi_steckdose.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
        icon_template: mdi:clipboard-pulse-outline

- platform: uptime
  name: online_time
  unit_of_measurement: hours 

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'

# - platform: glances
#   host: 127.0.0.1
#   username: !secret system_user
#   password: !secret system_password
#   version: 3
#   resources:
#     - disk_use_percent
#     - disk_use
#     - disk_free
#     - memory_use_percent
#     - memory_use
#     - memory_free
#     - processor_load
#     - process_running
#     - process_total 
#     - process_thread
#     - process_sleeping
#     - cpu_use_percent
#     - cpu_temp

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'