- platform: template
  switches:
    ###### Tastensperre für Heizung ######
    radiator_bed_room_keylock:
        friendly_name: "Tastensperre"
        value_template: "{{ is_state('sensor.radiator_bed_room_keylock', 'True') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1535747172583
        turn_off:
          - service: script.turn_on
            entity_id: script.1535747298118
        icon_template: >-
          {% if is_state('sensor.radiator_bed_room_keylock', 'True') %}
            mdi:lock-outline
          {% else %}
            mdi:lock-open-outline
          {% endif %}
    radiator_office_keylock:
        friendly_name: "Tastensperre"
        value_template: "{{ is_state('sensor.radiator_office_keylock', 'True') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1535749599600
        turn_off:
          - service: script.turn_on
            entity_id: script.1535749633757
        icon_template: >-
          {% if is_state('sensor.radiator_office_keylock', 'True') %}
            mdi:lock-outline
          {% else %}
            mdi:lock-open-outline
          {% endif %}
    radiator_living_room_keylock:
        friendly_name: "Tastensperre"
        value_template: "{{ is_state('sensor.radiator_living_room_keylock', 'True') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1535749160991
        turn_off:
          - service: script.turn_on
            entity_id: script.1535749518298
        icon_template: >-
          {% if is_state('sensor.radiator_living_room_keylock', 'True') %}
            mdi:lock-outline
          {% else %}
            mdi:lock-open-outline
          {% endif %}
    radiator_bath_keylock:
        friendly_name: "Tastensperre"
        value_template: "{{ is_state('sensor.radiator_bath_keylock', 'True') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538501968289
        turn_off:
          - service: script.turn_on
            entity_id: script.1538502054685
        icon_template: >-
          {% if is_state('sensor.radiator_bath_keylock', 'True') %}
            mdi:lock-outline
          {% else %}
            mdi:lock-open-outline
          {% endif %}
    radiator_on_off:
        friendly_name: "Heizungsschaltung"
        value_template: "{{ is_state('input_boolean.radiator_on_off', 'on') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1540232132608
        turn_off:
          - service: script.turn_on
            entity_id: script.1541264856783
        icon_template: >-
          {% if is_state('input_boolean.radiator_on_off', 'on')  %}
            mdi:radiator
          {% else %}
            mdi:radiator-off
          {% endif %}
    ###### Fernbedienung ######
    samsung_tv:
        friendly_name: "Samsung UE55J6200"
        value_template: "{{ is_state('device_tracker.ue55j6250', 'home') and is_state('light.steckdose', 'on') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538167144011
        turn_off:
          - service: script.turn_on
            entity_id: script.1538128738934
        icon_template: mdi:television
    avr_151:
        friendly_name: "AVR 151"
        value_template: "{{ is_state('device_tracker.avr151', 'home') and is_state('light.steckdose', 'on') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538167294875
        turn_off:
          - service: script.turn_on
            entity_id: script.1538129107690
        icon_template: mdi:speaker
    telekom_mr_401:
        friendly_name: "Telekom MR 401"
        value_template: "{{ is_state('device_tracker.telekom_mr401', 'home') and is_state('light.steckdose', 'on')}}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538167052403
        turn_off:
          - service: script.turn_on
            entity_id: script.1538143115062
        icon_template: mdi:youtube-tv
    tv_switch:
        friendly_name: "Fernsehen"
        value_template: "{{ is_state('sensor.remote_state', 'Fernsehen Telekom') and is_state('light.steckdose', 'on')}}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538068809592
        turn_off:
          - service: script.turn_on
            entity_id: script.1538057479069
    music_switch:
        friendly_name: "Musik"
        value_template: "{{ is_state('sensor.remote_state', 'Musik') and is_state('light.steckdose', 'on')}}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538072504227
        turn_off:
          - service: script.turn_on
            entity_id: script.1538057479069
    ###### Steckdosen (nur für HomeKit/Alexa) ######
    power_plug_multimedia:
        friendly_name: Steckdosenleiste
        value_template: "{{ is_state('light.steckdose', 'on') }}"
        turn_on:
          - service: light.turn_on
            entity_id: light.steckdose
        turn_off:
          - service: light.turn_off
            entity_id: light.steckdose
    power_plug_printer:
        friendly_name: Drucker
        value_template: "{{ is_state('light.steckdose_3', 'on') }}"
        turn_on:
          - service: light.turn_on
            entity_id: light.steckdose_3
        turn_off:
          - service: light.turn_off
            entity_id: light.steckdose_3
    power_plug_plug_3:
        friendly_name: Steckdose 3
        value_template: "{{ is_state('light.steckdose_5', 'on') }}"
        turn_on:
          - service: light.turn_on
            entity_id: light.steckdose_5
        turn_off:
          - service: light.turn_off
            entity_id: light.steckdose_5
