# lovelace_gen
  
# swipe_nav:
# -----------------------------
popup_cards:
  !include lovelace/includes/popup_cards.yaml
# -----------------------------
title: Home
views:
##### Licht #####
  # - !include lovelace/views_entities/light.yaml

##### Heizung #####
  # - !include lovelace/views_entities/radiator.yaml

##### Musik #####
  # - !include lovelace/views_entities/music.yaml

##### Entertainment #####
  # - !include lovelace/views_entities/entertainment.yaml

##### Steckdosen #####
  # - !include lovelace/views_entities/power_plug.yaml

##### Home #####
  # - !include lovelace/views_rooms/view_home.yaml

##### Wohnzimmer #####
  - !include lovelace/views_rooms/view_living_room.yaml

##### Büro #####
  - !include lovelace/views_rooms/view_office.yaml

##### Schlafzimmer #####
  - !include lovelace/views_rooms/view_bed_room.yaml

# ##### Büro #####
#   - !include lovelace/views_rooms/view_office.yaml

##### Küche #####
  - !include lovelace/views_rooms/view_kitchen.yaml

##### Bad #####
  - !include lovelace/views_rooms/view_bath.yaml

# ##### Flur #####
  - !include lovelace/views_rooms/view_floor.yaml

#### Staubsauger #####
  - !include lovelace/views_entities/vacuum.yaml