resources:
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/group-card/group-card.js
    type: js  
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: js
  - url: /local/github/thomasloven/time-input-row.js?track=true 
    type: js
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: js
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
    type: js
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/community/button-entity-row/button-entity-row_temp.js?v=0.05
    type: module
  - url: /hacsfiles/lovelace-more-info-card/more-info-card.js
    type: module
  - url: /hacsfiles/swipe-card/swipe-card.js
    type: module
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module

# -----------------------------
custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--primary-color)
  tab_indicator_color: var(--primary-color)
  chevrons: false
  hide_config: true
  shadow: true 
  default_tab: >-
    {% if not is_state('input_boolean.room_view','on') %}home
    {% else %}light
    {% endif %}
  hide_tabs: >-
    {% if not is_state('input_boolean.room_view','on') %}home, living_room, bed_room, office, bath, hass, kitchen, floor{% if not is_state('input_boolean.presence_map','on') %}, map{% endif %}
    {% else %}light, radiator, music, entertainment, power_plug{% if not is_state('input_boolean.presence_map','on') %}, map{% endif %}
    {% endif %}
  exceptions:
    - conditions:
        user: anita
      config:
        hide_unused: true
  
swipe_nav:
# -----------------------------
popup_cards:
  !include lovelace/includes/popup_cards.yaml
# -----------------------------
title: Home
views:
##### Home #####
  - !include lovelace/views_rooms/view_home.yaml

##### Licht #####
  - !include lovelace/views_entities/light.yaml

##### Heizung #####
  - !include lovelace/views_entities/radiator.yaml

##### Musik #####
  - !include lovelace/views_entities/music.yaml

##### Entertainment #####
  - !include lovelace/views_entities/entertainment.yaml

##### Wohnzimmer #####
  - !include lovelace/views_rooms/view_living_room.yaml

##### Schlafzimmer #####
  - !include lovelace/views_rooms/view_bed_room.yaml

##### Küche #####
  - !include lovelace/views_rooms/view_kitchen.yaml

##### Büro #####
  - !include lovelace/views_rooms/view_office.yaml

##### Bad #####
  - !include lovelace/views_rooms/view_bath.yaml

##### Flur #####
  - !include lovelace/views_rooms/view_floor.yaml

##### Steckdosen #####
  - !include lovelace/views_entities/power_plug.yaml

#### Staubsauger #####
  - !include lovelace/views_entities/vacuum.yaml
              
##### Personen #####
  - !include lovelace/views_entities/presence.yaml

##### Auto ##### 
  - !include lovelace/views_entities/car.yaml

##### Hass #####
  - !include lovelace/views_rooms/view_hass.yaml

##### System #####
  - !include lovelace/views_entities/system.yaml

##### Karte #####
  - !include lovelace/views_entities/map.yaml