resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/group-card/group-card.js
    type: js  
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: /local/github/thomasloven/time-input-row.js?track=true 
    type: js
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: js
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
    type: js
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: module

# -----------------------------
custom_header:
  compact_mode: true
  chevrons: false
  hide_config: true

swipe_nav:
# -----------------------------

# -----------------------------
## Views
title: Home
views:
##### Licht #####
  - !include lovelace/light.yaml

##### Heizung #####
  - !include lovelace/radiator.yaml

#### Staubsauger #####
  - !include lovelace/vacuum.yaml

##### Musik #####
  - !include lovelace/music.yaml

##### Entertainment #####
  - !include lovelace/entertainment.yaml

##### Steckdosen #####
  - !include lovelace/power_plug.yaml
                
##### Personen #####
  - !include lovelace/presence.yaml

##### Auto ##### 
  - !include lovelace/car.yaml

##### System #####
  - !include lovelace/system.yaml