# lovelace_gen
  
swipe_nav:

button_card_templates: !include lovelace/includes/button_card_templates.yaml

title: Home
views:
###### Übersicht #####
  - !include lovelace/ui-overview.yaml

##### Wohnzimmer #####
  - !include lovelace/views_rooms/view_living_room.yaml

##### Büro #####
  # - !include lovelace/views_rooms/view_office.yaml

##### Schlafzimmer #####
  - !include lovelace/views_rooms/view_bed_room.yaml

##### Küche #####
  - !include lovelace/views_rooms/view_kitchen.yaml

##### Bad #####
  - !include lovelace/views_rooms/view_bath.yaml

###### Flur #####
  - !include lovelace/views_rooms/view_floor.yaml