# lovelace_gen
  
swipe_nav:
# -----------------------------
popup_cards:
  !include lovelace/includes/popup_cards.yaml
# -----------------------------
title: Home
views:
##### Wohnzimmer #####
  - !include lovelace/views_rooms/view_living_room.yaml

##### Büro #####
  - !include lovelace/views_rooms/view_office.yaml

##### Schlafzimmer #####
  - !include lovelace/views_rooms/view_bed_room.yaml

##### Küche #####
  - !include lovelace/views_rooms/view_kitchen.yaml

##### Bad #####
  - !include lovelace/views_rooms/view_bath.yaml

# ##### Flur #####
  - !include lovelace/views_rooms/view_floor.yaml

#### Staubsauger #####
  - !include lovelace/views_entities/vacuum_2.yaml