# lovelace_gen

title: Karte

custom_header:
  compact_mode: false

views:
  - title: Karte
    visible:
      - user: b6464705fc4e405abce8058610b4bcc7
    path: map
    icon: mdi:map
    panel: true
    cards:
      - type: map
        default_zoom: 15
        entities:
          - entity: device_tracker.iphone11pro_2
          - entity: device_tracker.x1_sdrive18i
          - zone.home
          - zone.agcs