# lovelace_gen

title: System

views:
  - title: System
    visible:
      - user: b6464705fc4e405abce8058610b4bcc7
    path: system
    icon: mdi:settings-outline
    # panel: true
    # cards:
    #   - type: custom:layout-card
    #     max_columns: 2
    cards:
      - type: entities
        entities:
          - type: 'custom:paper-buttons-row'
            buttons:
              - entity: script.1570443737111
                name: Mitteilung löschen
                style:
                  text:  
                    color: var(--primary-text-color)
              - entity: script.1570439203461
                name: Badge löschen
                style:
                  text:  
                    color: var(--primary-text-color)
      - type: entities
        entities:
          - entity: switch.ds118
            icon: mdi:nas
            tap_action: 
              action: toggle
      - type: entities
        show_header_toggle: false
        entities:
          - entity: automation.tagliches_backup_auto_backup
            icon: mdi:content-save-all
            tap_action: 
              action: toggle
          - sensor.auto_backup
      - type: entities
        show_header_toggle: false
        entities:
          - entity: automation.starte_raspberry_full_backup
            icon: mdi:server
            tap_action: 
              action: toggle
      - type: entities
        entities:
          - entity: automation.battery_persistent_notification
            tap_action: 
              action: toggle
          - entity: script.battery_persistent_notification_clear
            tap_action: 
              action: toggle
          - type: custom:fold-entity-row
            head:
              type: section
              label: Batteriewerte
            padding: 5
            entities:
              - input_number.battery_alert_xiaomi
              - input_number.battery_alert_hue
          - type: custom:fold-entity-row
            head:
              type: section
              label: Batteriestatus
            padding: 5
            entities:
              - group.battery_status_hue
              - group.battery_status_xiaomi
      - type: glance
        columns: 4
        show_name: false
        entities:
          - entity: sensor.memory_use_percent
            name: Memory
          - entity: sensor.memory_use
            name: Memory
          - entity: sensor.disk_use_percent
            name: Disk
          - entity: sensor.disk_use
            name: Disk
          - entity: sensor.swap_use_percent
            name: Swap
            icon: mdi:harddisk-plus
          - entity: sensor.processor_use
            name: CPU
            icon: mdi:chip
          - entity: sensor.cpu_temperature
            name: CPU Temp
            icon: mdi:thermometer
          - entity: sensor.online_time
            name: Zeit
      - type: glance
        columns: 4
        show_name: false
        entities:
          - sensor.net_download_max
          - sensor.net_download_cur
          - sensor.fritz_netmonitor
          - sensor.net_uptime
          - sensor.net_upload_max
          - sensor.net_upload_cur
          - sensor.fritzbox
      - type: entities  
        entities:
          - entity: switch.pi_hole
            icon: mdi:pi-hole
            tap_action: 
              action: toggle
            hold_action: 
                action: call-service
                service: browser_mod.popup
                service_data:
                  deviceID: this
                  title: PI-Hole Stats
                  card:
                    type: custom:auto-entities
                    card:
                      type: entities 
                    filter:
                        include:
                          - entity_id: "sensor.pi_hole_*"
      - type: entities
        entities:
          - type: "custom:paper-buttons-row"
            buttons:
              # - entity: input_boolean.room_view
              #   name: false
              - entity: switch.frontend
                name: false
              - entity: switch.hass_io_addon_glances
                name: false
                icon: mdi:speedometer
              - entity: switch.hass_io_addon_grafana
                name: false
                icon: mdi:chart-timeline
              - icon: mdi:script-text
                name: false
                tap_action: 
                  action: call-service
                  service: browser_mod.navigate
                  service_data: 
                    navigation_path: /config/script
                    deviceID: this
              - icon: mdi:robot
                name: false
                tap_action: 
                  action: call-service
                  service: browser_mod.navigate
                  service_data: 
                    navigation_path: /config/automation
                    deviceID: this
              - icon: mdi:map-outline
                name: false
                tap_action: 
                  action: call-service
                  service: browser_mod.navigate
                  service_data: 
                    navigation_path: /lovelace-map/map
                    deviceID: this
        