# lovelace_gen

title: Anwesenheit

views:
  - title: Personen
    path: presence
    icon: mdi:account-multiple
    type: custom:horizontal-layout
    layout:
      max_cols: 2
      height: auto
    cards:
      - square: false
        type: grid
        cards:
          - type: tile
            entity: person.wolfgang
          - type: tile
            entity: person.christina
          - type: tile
            entity: automation.abwesenheit
            tap_action:
              action: toggle
            icon_tap_action:
              action: toggle
        columns: 2