# lovelace_gen

type: entities
entities:
  - type: "custom:paper-buttons-row"
    buttons:
      - entity: script.sonos_radio_superfly
        name: Sonos einschalten
        style:
          text:  
            color: var(--primary-text-color)
      - entity: script.1532175994947
        name: Sonos ausschalten
        style:
          text:  
            color: var(--primary-text-color)