- platform: template
  sensors:
##############################################################
# Homematic 
##############################################################
      # battery_radiator_office_1:
      #   entity_id: climate.oeq1667238
      #   friendly_name: "Batterie Thermostat Büro"
      #   value_template: '{{ states.climate.oeq1667238.attributes.battery }}'
      # battery_radiator_office_2:
      #   entity_id: climate.oeq1714751
      #   friendly_name: "Batterie Heizung Büro"
      #   value_template: '{{ states.climate.oeq1714751.attributes.battery }}'
      # battery_radiator_bedroom:
      #   entity_id: climate.oeq1696369
      #   friendly_name: "Batterie Heizung Schlafzimmer"
      #   value_template: '{{ states.climate.oeq1696369.attributes.battery }}'
      # battery_radiator_livingroom:
      #   entity_id: climate.oeq1696358
      #   friendly_name: "Batterie Heizung Wohnzimmer"
      #   value_template: '{{ states.climate.oeq1696358.attributes.battery }}'
##############################################################
# Xiaomi
##############################################################
      battery_sensor_bedroom:
        entity_id: sensor.xiaomi_bed_room_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Schlafzimmer"
        value_template: '{{ states.sensor.xiaomi_bed_room_battery_level.state }}'
      battery_sensor_livingroom:
        entity_id: sensor.xiaomi_living_room_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Wohnzimmer"
        value_template: '{{ states.sensor.xiaomi_living_room_battery_level.state }}'
      battery_sensor_kitchen:
        entity_id: sensor.xiaomi_kitchen_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Küche"
        value_template: '{{ states.sensor.xiaomi_kitchen_battery_level.state }}'
      battery_sensor_bath:
        entity_id: sensor.xiaomi_bath_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Bad"
        value_template: '{{ states.sensor.xiaomi_bath_battery_level.state }}'
      battery_sensor_motion:
        entity_id: sensor.lightlevel_20_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Motion"
        value_template: '{{ states.sensor.lightlevel_20_battery_level.state }}'
      battery_sensor_door:
        entity_id: sensor.openclose_29_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Motion Door/Window"
        value_template: '{{ states.sensor.openclose_29_battery_level.state }}'
      battery_sensor_button_1:
        entity_id: sensor.smart_switch_1_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Button 1"
        value_template: '{{ states.sensor.smart_switch_1_battery_level.state }}'
      battery_sensor_button_2:
        entity_id: sensor.smart_switch_2_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Button 2"
        value_template: '{{ states.sensor.smart_switch_2_battery_level.state }}'
      battery_sensor_wall_switch:
        entity_id: sensor.wandsender_1_fach_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Wall Switch"
        value_template: '{{ states.sensor.wandsender_1_fach_battery_level.state }}'      
      battery_sensor_wall_switch_double:
        entity_id: sensor.wandsender_2_fach_battery_level
        device_class: battery
        friendly_name: "Batterie Sensor Wall Switch Double"
        value_template: '{{ states.sensor.wandsender_2_fach_battery_level.state }}'
##############################################################
# Hue
##############################################################
      hue_dimmer_battery_bedroom:
        entity_id: sensor.dimmschalter_schlafzimmer_battery_level
        friendly_name: Hue dimmer Schlafzimmer
        device_class: battery
        value_template: '{{ states.sensor.dimmschalter_schlafzimmer_battery_level.state }}'
      hue_dimmer_battery_livingroom:
        entity_id: sensor.dimmschalter_battery_level
        friendly_name: Hue dimmer Wohnzimmer
        device_class: battery
        value_template: '{{ states.sensor.dimmschalter_battery_level.state }}'
##############################################################
# Fritz Smart Home
##############################################################
      # fritz_thermostat_1_battery:
      #   entity_id: climate.fritz_thermostat
      #   friendly_name: Fritz Thermostat 
      #   device_class: battery
      #   value_template: '{{ states.climate.fritz_thermostat.attributes.battery_level }}'