- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'

- platform: rest
  unique_id: nextcloud_update
  name: nextcloud_update
  scan_interval: 1200
  # device_class: update
  resource: https://www.tanzer-online.com/nextcloud_fixes/update_check.php
  json_attributes:
      - state
      - desc
  value_template: "{{ value_json.state }}"
