- platform: systemmonitor
  resources:
      - type: memory_free
      - type: memory_use
      - type: memory_use_percent
      - type: processor_use
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: load_1m 
      - type: load_5m
      - type: load_15m
      - type: swap_use
      - type: swap_free
      - type: swap_use_percent
      - type: last_boot

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  unique_id: pihole
  name: pihole
  scan_interval: 10
  command: curl -s -X GET 'http://192.168.200.33:88/admin/api.php?status&auth=d150ea5c83cfc740a884f6d2ced8c836a2d65504c438002cda5cc023dd71d8c6'
  value_template: >
    {{ value_json.status }}

- platform: command_line
  unique_id: nextcloud_version
  name: nextcloud_version
  scan_interval: 21600
  command: curl -s -X GET 'https://next.tanzer-online.com/status.php'
  value_template: >
    {{ value_json.versionstring }}