- platform: fritzbox_netmonitor
  host: 192.168.200.1

- platform: fritzbox_callmonitor
  host: 192.168.200.1
  name: fritzbox
  username: !secret fritz_user
  password: !secret fritz_password
  prefixes:
    - '+49'

- platform: systemmonitor
  resources:
      - type: memory_free
      - type: memory_use
      - type: memory_use_percent
      - type: processor_use
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: load_1m 
      - type: load_5m
      - type: load_15m
      - type: swap_use
      - type: swap_free
      - type: swap_use_percent

- platform: template
  sensors:
      remote_state:
        # entity_id:  remote.harmony_hub
        friendly_name: "Multimedia"
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      presence:
        # entity_id:  person.wolfgang
        friendly_name: Anwesenheit
        value_template: >
            {% if is_state('person.wolfgang', 'home') or is_state('person.christina', 'home') %}
              home
            {% else %}
              not_home
            {% endif %}
      wireguard_iphonepro:
        friendly_name: "Wireguard iPhone 11 Pro"
        value_template: >-
            {% if state_attr('sensor.wireguard', 'iphonepro').latest_handshake > ( as_timestamp(now()) ) -60 %}
              Connected
            {% else %}
              Disconnected
            {% endif %}
        icon_template: >-
            {% if state_attr('sensor.wireguard', 'iphonepro').latest_handshake > ( as_timestamp(now()) ) -60 %}
              mdi:network
            {% else %}
              mdi:network-off
            {% endif %}
      wireguard_ipad:
        friendly_name: "Wireguard iPad"
        value_template: >-
            {% if state_attr('sensor.wireguard', 'ipad').latest_handshake > ( as_timestamp(now()) ) -60 %}
              Connected
            {% else %}
              Disconnected
            {% endif %}
        icon_template: >-
            {% if state_attr('sensor.wireguard', 'ipad').latest_handshake > ( as_timestamp(now()) ) -60 %}
              mdi:network
            {% else %}
              mdi:network-off
            {% endif %}

- platform: uptime
  name: online_time
  unit_of_measurement: hours 

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: pihole
  scan_interval: 10
  command: curl -X GET 'http://192.168.200.33:88/admin/api.php?status'
  value_template: >
    {{ value_json.status }}

- platform: rest
  name: wireguard
  resource: http://a0d7b954-wireguard
  json_attributes:
  - iphonepro
  - ipad
  value_template: "OK"