- platform: template
  sensors:
      xiaomi_vacuum_status:
        # entity_id:  vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Status"
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}'
      xiaomi_vacuum_main_brush_left:
        # entity_id:  vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Main Brush"
        unit_of_measurement: 'h'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}'
      xiaomi_vacuum_side_brush_left:
        # entity_id:  vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Side Brush"
        unit_of_measurement: 'h'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}'
      xiaomi_vacuum_filter_left:
        # entity_id:  vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Filter"
        unit_of_measurement: 'h'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}'
      xiaomi_vacuum_sensor_dirty_left:
        # entity_id:  vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Sensor"
        unit_of_measurement: 'h'
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }}'
      xiaomi_vacuum_sensor_battery:
        # entity_id:  vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Staubsauger Batterie"
        unit_of_measurement: '%'
        device_class: battery
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}'
        icon_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon }}'