# unused automations

- id: scenes_living_room
  alias: 'Lichtszenen: Wohnzimmer ausw채hlen'
  trigger:
  - entity_id: input_select.scenes_living_room
    platform: state
  condition:
  - condition: template
    value_template: '{{ states.input_select.scenes_living_room.state != "--" }}'
  action:
  - data_template:
      entity_id: scene.wohnzimmer_{{ states.input_select.scenes_living_room.state
        | replace(' ', '_') | lower | string }}
    service: scene.turn_on
  - data:
      entity_id: input_select.scenes_living_room
      option: --
    service: input_select.select_option
- id: scenes_bed_room
  alias: 'Lichtszenen: Schlafzimmer ausw채hlen'
  trigger:
  - entity_id: input_select.scenes_bed_room
    platform: state
  condition:
  - condition: template
    value_template: '{{ states.input_select.scenes_bed_room.state != "--" }}'
  action:
  - data_template:
      entity_id: scene.schlafzimmer_{{ states.input_select.scenes_bed_room.state |
        replace(' ', '_') | lower | string }}
    service: scene.turn_on
  - data:
      entity_id: input_select.scenes_bed_room
      option: --
    service: input_select.select_option
- id: scenes_reset_living_room
  alias: 'Lichtszenen: Wohnzimmer zur체cksetzen'
  trigger:
    platform: state
    entity_id: light.lights_living_room
    from: 'on'
    to: 'off'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.scenes_living_room
      option: --
- id: scenes_reset_bed_room
  alias: 'Lichtszenen: Schlafzimmer zur체cksetzen'
  trigger:
    platform: state
    entity_id: light.schlafzimmer
    from: 'on'
    to: 'off'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.scenes_bed_room
      option: --
- id: '1573989717339'
  alias: Heizung Offset Schlafzimmer
  description: ''
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
  - data_template:
      climate: OEQ1696369
      input_offset: input_number.offset_bed_room
      offset: '{{ states.sensor.offset_bed_room.state | float  }}'
      target_temp: '{{ states.climate.oeq1696369.attributes.temperature }}'
    service: python_script.set_thermostate_offset
- id: '1573989784804'
  alias: Heizung Offset Wohnzimmer
  description: ''
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
  - data_template:
      climate: OEQ1696358
      input_offset: input_number.offset_living_room
      offset: '{{ states.sensor.offset_living_room.state | float  }}'
      target_temp: '{{ states.climate.oeq1696358.attributes.temperature }}'
    service: python_script.set_thermostate_offset