- platform: ffmpeg
  input: -rtsp_transport tcp -i rtsp://192.168.200.40:554/onvif1

- platform: xiaomi_cloud_map_extractor
  host: 192.168.200.29
  token: !secret xiaomi_vacuum
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw: ['all']
  auto_update: false
  attributes:
    - calibration_points
  # colors:
  #   color_map_outside: [3, 169, 244]
  map_transformation:
    trim:
      top: 10
      bottom: 10
      left: 10
      right: 10