#### Sonoff ####
# - platform: mqtt
#   name: "sonoff_office"
#   state_topic: "stat/sonoff/POWER"
#   command_topic: "cmnd/sonoff/POWER"
#   availability_topic: "tele/sonoff/LWT"
#   qos: 1
#   payload_on: "ON"
#   payload_off: "OFF"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   retain: true
  
#### groups ####
- platform: group
  name: lights_living_room
  entities:
      - light.decke
      - light.tisch
      # - light.leselampe

- platform: group
  name: schlafzimmer
  entities:
      - light.schlafzimmer_1
      - light.schlafzimmer_2

- platform: group
  name: lights_bed_room
  entities:
      - light.schlafzimmer
      - light.nachttischlampe_wolfgang

- platform: group
  name: lights_office
  entities:
      - light.sonoff_office     

- platform: group
  name: lights_kitchen
  entities:
      - light.deckenlicht
      - light.steckdose_4

- platform: group
  name: lights_all
  entities:
      - light.decke
      - light.tisch
      - light.leselampe
      - light.schlafzimmer
      # - light.gateway_light_7811dcb258d1
      # - light.sonoff_office
      - light.nachttischlampe_wolfgang
      - light.deckenlicht
      - light.steckdose_4

# Küchenlichtschalter
- platform: switch
  name: steckdose_4
  entity_id: switch.steckdose_4