- platform: template
  switches:
###### Fernbedienung ######
    samsung_tv:
      unique_id: samsung_tv_switch
      friendly_name: "Samsung TV"
      value_template: "{{ is_state('media_player.samsung_q60aa_43_tv', 'on') and is_state('switch.steckdosenleiste', 'on') }}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_tv_power_on
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_tv_power_off
      icon_template: mdi:television
    avr_151:
      unique_id: avr_151_switch
      friendly_name: "AVR 151"
      value_template: "{{ is_state('device_tracker.avr_151s', 'home') and is_state('switch.steckdosenleiste', 'on') }}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_avr_power_on
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_avr_power_off
      icon_template: mdi:speaker
    appletv:
      unique_id: appletv_switch
      friendly_name: "Apple TV"
      value_template: "{{ is_state('sensor.remote_state', 'Apple TV')  }}"
      turn_on:
        - service: select.select_option
          target:
            entity_id: select.harmony_hub_2_activities
          data:
            option: Apple TV
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_avr_power_off
      icon_template: si:appletv
    airplay:
      unique_id: airplay_switch
      friendly_name: "AirPlay"
      value_template: "{{ is_state('sensor.remote_state', 'AirPlay')  }}"
      turn_on:
        - service: select.select_option
          target:
            entity_id: select.harmony_hub_2_activities
          data:
            option: AirPlay
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_avr_power_off
      icon_template: si:airplayvideo

###############################################

    vacuum:
      unique_id: vacuum_switch
      friendly_name: Staubsauger
      value_template: "{{ is_state('vacuum.roborock_vacuum', 'cleaning')}}"
      turn_on:
        - service: vacuum.start
          entity_id: vacuum.roborock_vacuum
      turn_off:
        - service: vacuum.return_to_base
          entity_id: vacuum.roborock_vacuum

###############################################
    pi_hole_switch:
      friendly_name: "Pi-hole"
      value_template: "{{ is_state('binary_sensor.pi_hole', 'on') }}"
      turn_on:
        - service: switch.turn_on
          data: {}
          target:
            entity_id: switch.pi_hole
        - service: homeassistant.update_entity
          data: {}
          target:
            entity_id: binary_sensor.pi_hole
      turn_off:
        - service: pi_hole.disable
          data:
            duration: "{{states.input_datetime.pi_hole_timer.state}}"
          target:
            device_id: 75c3e5a3dc174da39882183a70fc7e1a
        - service: homeassistant.update_entity
          data: {}
          target:
            entity_id: binary_sensor.pi_hole
###############################################
    ds114:
      unique_id: ds114
      friendly_name: DS114
      value_template: "{{ is_state('device_tracker.wireguard_ds114', 'home')}}"
      turn_on:
        - service: shell_command.ds114_wol
      turn_off:
        - service: button.press
          target:
            entity_id: button.ds114_shutdown
        
- platform: wake_on_lan
  mac: 00:11:32:98:83:61
  host: 192.168.200.41
  name: DS118
  turn_off:
    service: button.press
    target:
      entity_id: button.ds118_shutdown