- platform: template
  switches:
    ###### Fernbedienung ######
    samsung_tv:
      friendly_name: "Samsung UE55J6200"
      value_template: "{{ is_state('device_tracker.ue55j6250', 'home') and is_state('switch.steckdose_1', 'on') }}"
      turn_on:
        - service: script.turn_on
          entity_id: script.1538167144011
      turn_off:
        - service: script.turn_on
          entity_id: script.1538128738934
      icon_template: mdi:television
    avr_151:
      friendly_name: "AVR 151"
      value_template: "{{ is_state('device_tracker.avr151', 'home') and is_state('switch.steckdose_1', 'on') }}"
      turn_on:
        - service: script.turn_on
          entity_id: script.1538167294875
      turn_off:
        - service: script.turn_on
          entity_id: script.1538129107690
      icon_template: mdi:speaker
    telekom_mr_401:
      friendly_name: "Telekom MR 401"
      value_template: "{{ is_state('device_tracker.telekom_mr401', 'home') and is_state('switch.steckdose_1', 'on')}}"
      turn_on:
        - service: script.turn_on
          entity_id: script.1538167052403
      turn_off:
        - service: script.turn_on
          entity_id: script.1538143115062
      icon_template: mdi:youtube-tv
    tv_switch:
      friendly_name: "Magenta TV"
      value_template: "{{ is_state('sensor.remote_state', 'Magenta TV') and is_state('switch.steckdose_1', 'on')}}"
      turn_on:
        - service: script.turn_on
          entity_id: script.1538068809592
      turn_off:
        - service: script.turn_on
          entity_id: script.1538057479069
    fire_tv_switch:
      friendly_name: "Fire TV"
      value_template: "{{ is_state('sensor.remote_state', 'Fire TV') and is_state('switch.steckdose_1', 'on')}}"
      turn_on:
        - service: script.turn_on
          entity_id: script.1586021623720
      turn_off:
        - service: script.turn_on
          entity_id: script.1538057479069
    music_switch:
      friendly_name: "Musik"
      value_template: "{{ is_state('sensor.remote_state', 'Musik') and is_state('switch.steckdose_1', 'on')}}"
      turn_on:
        - service: script.turn_on
          entity_id: script.1538072504227
      turn_off:
        - service: script.turn_on
          entity_id: script.1538057479069
    vacuum:
      friendly_name: Staubsauger
      value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning')}}"
      turn_on:
        - service: vacuum.start
          entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        - service: vacuum.return_to_base
          entity_id: vacuum.xiaomi_vacuum_cleaner
    ###############################################
    ###### Sonstiges ######
    pi_hole_switch:
      friendly_name: "Pi-hole"
      value_template: "{{ is_state('sensor.pihole', 'enabled') }}"
      turn_on:
        service: pi_hole.enable
      turn_off:
        service: pi_hole.disable
        data:
          duration: '12:00:00'

###############################################
- platform: wake_on_lan
  mac: 00:11:32:98:83:61
  name: DS118
  host: 192.168.200.41
  turn_off:
    service: shell_command.restart_ds118