- platform: template
  switches:
    ###### Fernbedienung ######
    samsung_tv:
        friendly_name: "Samsung UE55J6200"
        value_template: "{{ is_state('device_tracker.ue55j6250', 'home') and is_state('switch.wifi_steckdose', 'on') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538167144011
        turn_off:
          - service: script.turn_on
            entity_id: script.1538128738934
        icon_template: mdi:television
    avr_151:
        friendly_name: "AVR 151"
        value_template: "{{ is_state('device_tracker.avr151', 'home') and is_state('switch.wifi_steckdose', 'on') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538167294875
        turn_off:
          - service: script.turn_on
            entity_id: script.1538129107690
        icon_template: mdi:speaker
    telekom_mr_401:
        friendly_name: "Telekom MR 401"
        value_template: "{{ is_state('device_tracker.telekom_mr401', 'home') and is_state('switch.wifi_steckdose', 'on')}}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538167052403
        turn_off:
          - service: script.turn_on
            entity_id: script.1538143115062
        icon_template: mdi:youtube-tv
    tv_switch:
        friendly_name: "Magenta TV"
        value_template: "{{ is_state('sensor.remote_state', 'Magenta TV') and is_state('switch.wifi_steckdose', 'on')}}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538068809592
        turn_off:
          - service: script.turn_on
            entity_id: script.1538057479069
    fire_tv_switch:
        friendly_name: "Fire TV"
        value_template: "{{ is_state('sensor.remote_state', 'Fire TV') and is_state('switch.wifi_steckdose', 'on')}}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1586021623720
        turn_off:
          - service: script.turn_on
            entity_id: script.1538057479069
    music_switch:
        friendly_name: "Musik"
        value_template: "{{ is_state('sensor.remote_state', 'Musik') and is_state('switch.wifi_steckdose', 'on')}}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538072504227
        turn_off:
          - service: script.turn_on
            entity_id: script.1538057479069
    ###### Switches (nur für HomeKit/Alexa) ######
    # power_plug_printer:
    #     friendly_name: Drucker
    #     value_template: "{{ is_state('switch.steckdose_3', 'on') }}"
    #     turn_on:
    #       - service: light.turn_on
    #         entity_id: switch.steckdose_3
    #     turn_off:
    #       - service: light.turn_off
    #         entity_id: switch.steckdose_3
    # power_plug_5:
    #     friendly_name: Steckdose 5
    #     value_template: "{{ is_state('switch.steckdose_5', 'on') }}"
    #     turn_on:
    #       - service: switch.turn_on
    #         entity_id: switch.steckdose_5
    #     turn_off:
    #       - service: switch.turn_off
    #         entity_id: switch.steckdose_5
    vacuum:
        friendly_name: Staubsauger
        value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning')}}"
        turn_on:
          - service: vacuum.start
            entity_id: vacuum.xiaomi_vacuum_cleaner
        turn_off:
          - service: vacuum.return_to_base
            entity_id: vacuum.xiaomi_vacuum_cleaner
    ###############################################
    ###### Sonstiges ######
    frontend:
        friendly_name: "Erscheinungsbild"
        value_template: "{{ is_state('input_boolean.frontend', 'on') }}"
        turn_on:
          - service: automation.trigger
            entity_id: automation.frontend_nacht
        turn_off:
          - service: automation.trigger
            entity_id: automation.frontend_tag
        icon_template: >-
          {% if is_state('input_boolean.frontend', 'on')  %}
            mdi:brightness-2
          {% else %}
            mdi:brightness-5
          {% endif %}

###############################################
- platform: wake_on_lan
  mac: 00:11:32:98:83:61
  name: DS118
  host: 192.168.200.41
  turn_off:
    service: shell_command.restart_ds118