- platform: template
  switches:
###### Fernbedienung ######
    samsung_tv:
      unique_id: samsung_tv_switch
      friendly_name: "Samsung TV"
      value_template: "{{ is_state('media_player.samsung_q60aa_43_tv', 'on') and is_state('switch.steckdosenleiste', 'on') }}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_tv_power_on
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_tv_power_off
      icon_template: mdi:television
    avr_151:
      unique_id: avr_151_switch
      friendly_name: "AVR 151"
      value_template: "{{ is_state('device_tracker.avr_151s', 'home') and is_state('switch.steckdosenleiste', 'on') }}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_avr_power_on
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_avr_power_off
      icon_template: mdi:speaker
    telekom_mr_401:
      unique_id: telekom_mr_401_switch
      friendly_name: "Telekom MR 401"
      value_template: "{{ is_state('device_tracker.telekom_mr401', 'home') }}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_mr400_power_on
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_mr400_power_off
      icon_template: mdi:set-top-box
    tv_switch:
      unique_id: tv_switch
      friendly_name: "Magenta TV"
      value_template: "{{ is_state('sensor.remote_state', 'Magenta TV') and is_state('switch.steckdosenleiste', 'on')}}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_action_telekom
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_power_off
    fire_tv_switch:
      unique_id: fire_tv_switch
      friendly_name: "Fire TV"
      value_template: "{{ is_state('sensor.remote_state', 'Fire TV') and is_state('switch.steckdosenleiste', 'on')}}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_action_fire_tv
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_power_off
    music_switch:
      unique_id: music_switch
      friendly_name: "Plattenspieler"
      value_template: "{{ is_state('sensor.remote_state', 'Plattenspieler') and is_state('switch.steckdosenleiste', 'on')}}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_action_music
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_power_off
    vtuner_switch:
      unique_id: vtuner_switch
      friendly_name: "vTuner"
      value_template: "{{ is_state('sensor.remote_state', 'vTuner') and is_state('switch.steckdosenleiste', 'on')}}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_action_vtuner
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_power_off
    airplay_switch:
      unique_id: airplay_switch
      friendly_name: "AirPlay"
      value_template: "{{ is_state('sensor.remote_state', 'AirPlay') and is_state('switch.steckdosenleiste', 'on')}}"
      turn_on:
        - service: script.turn_on
          entity_id: script.harmony_action_airplay
      turn_off:
        - service: script.turn_on
          entity_id: script.harmony_power_off
###############################################
    vacuum:
      unique_id: vacuum_switch
      friendly_name: Staubsauger
      value_template: "{{ is_state('vacuum.roborock_vacuum', 'cleaning')}}"
      turn_on:
        - service: vacuum.start
          entity_id: vacuum.roborock_vacuum
      turn_off:
        - service: vacuum.return_to_base
          entity_id: vacuum.roborock_vacuum
###############################################
    pi_hole_switch:
      friendly_name: "Pi-hole"
      value_template: "{{ is_state('sensor.pihole', 'enabled') }}"
      turn_on:
        - service: switch.turn_on
          data: {}
          target:
            entity_id: switch.pi_hole
        - service: homeassistant.update_entity
          data: {}
          target:
            entity_id: sensor.pihole
      turn_off:
        - service: pi_hole.disable
          data:
            duration: "{{states.input_datetime.pi_hole_timer.state}}"
          target:
            device_id: 75c3e5a3dc174da39882183a70fc7e1a
        - service: homeassistant.update_entity
          data: {}
          target:
            entity_id: sensor.pihole

###############################################
- platform: wake_on_lan
  mac: 00:11:32:98:83:61
  host: 192.168.200.41
  name: DS118
  turn_off:
    service: shell_command.ds118_shutdown