{
 "title": "Raspberry",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Processor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "glances_cpu_used" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "processor_use_2" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "processor_use" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperatur",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "cpu_temperature" }
     ]
    }
   ]
  },
  {
   "title": "Speicher",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "alias": "Disk used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "GiB",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "disk_use" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "glances_disk_used" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "glances_disk_used_2" }
     ]
    },
    {
     "alias": "Disk free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "GiB",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "disk_free" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "MiB",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "glances_ram_used" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "glances_ram_used_2" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "memory_use" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "memory_use_2" }
     ]
    }
   ]
  },
  {
   "title": "RPI Online Zeit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "Online Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hours",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "online_time" }
     ]
    }
   ]
  }
 ]
}