# lovelace_gen

#### popup instead of more-info
popup_cards:
  sensor.samba_backup:
    title: Status
    card:
      type: entities
      entities:
        - attribute: backups_local
          entity: sensor.samba_backup
          icon: 'mdi:file-outline'
          name: Local Backups
          type: attribute
        - attribute: backups_remote
          entity: sensor.samba_backup
          icon: 'mdi:file-move-outline'
          name: Remote Backups
          type: attribute
        - attribute: total_backups_succeeded
          entity: sensor.samba_backup
          icon: 'mdi:file-check-outline'
          name: Succeded Backups
          type: attribute
        - attribute: total_backups_failed
          entity: sensor.samba_backup
          icon: 'mdi:file-cancel-outline'
          name: Failed Backups
          type: attribute
        - attribute: last_backup
          entity: sensor.samba_backup
          icon: 'mdi:file-clock-outline'
          name: Last Backup
          type: attribute

  automation.batterie_benachrichtigung:
    title: Batteriestatus
    card:
      type: custom:auto-entities
      card:
        type: entities 
      filter:
        include:
          - entity_id: "sensor.*_battery_level"
            options:
              type: custom:battery-entity-row
        exclude:
          - entity_id: "*iphone*"
          - entity_id: "*ipad*"

  switch.pi_hole:
    title: PI-Hole Stats
    card:
      type: custom:auto-entities
      card:
        type: entities 
      filter:
          include:
            - entity_id: "sensor.pi_hole_*"  
#### #### #### #### #### #### #### #### #### #### 

title: System

views:
  - title: System
    path: system
    icon: mdi:cog-outline
    type: custom:horizontal-layout
    layout:
      max_cols: 2
    cards:
      - type: entities
        entities:
          - type: 'custom:paper-buttons-row'
            buttons:
              - entity: script.notify_clean_messages
                name: Mitteilung löschen
              - entity: script.notify_clean_badge
                name: Badge löschen        
      - type: entities
        show_header_toggle: false
        entities:
          - entity:  sensor.updater_core
            type: custom:multiple-entity-row
            name: Core
            show_state: false
            icon: mdi:update
            entities:
              - attribute: current_version
                name: Installiert
              - attribute: newest_version
                name: Verfügbar
            tap_action: 
              action: fire-dom-event
              browser_mod:
                command: navigate
                navigation_path: /hassio
          - entity:  sensor.updater_supervisor
            type: custom:multiple-entity-row
            name: Supervisor
            icon: mdi:update
            show_state: false
            entities:
              - attribute: current_version
                name: Installiert
              - attribute: newest_version
                name: Verfügbar
            tap_action: 
              action: fire-dom-event
              browser_mod:
                command: navigate
                navigation_path: /hassio
          - entity:  sensor.updater_supervisor
            type: custom:multiple-entity-row
            name: Add-ons
            icon: mdi:update
            tap_action: 
              action: fire-dom-event
              browser_mod:
                command: navigate
                navigation_path: /hassio
          - entity: sensor.hacs
            name: Hacs
            tap_action: 
              action: fire-dom-event
              browser_mod:
                command: navigate 
                navigation_path: /hacs
          - type: custom:fold-entity-row
            padding: 5
            head:
              type: section
              label: Details
            entities:
              - entity: sensor.online_time
                name: Hass online
                icon: mdi:home-assistant
              - entity: sensor.last_boot
                name: Raspi online
                icon: mdi:raspberry-pi
      - type: glance
        columns: 5
        show_name: false
        entities:
          - entity: sensor.processor_use
            name: CPU   
            style: |
                :host {
                  color: 
                  {% if (states.sensor.processor_use.state | int) > 30 %}
                    red
                  {% endif %}
                  ;
                }     
          - entity: sensor.cpu_temperature
            icon: mdi:thermometer
            name: CPU Temp
            style: |
                :host {
                  color: 
                  {% if (states.sensor.cpu_temperature.state | int) > 70 %}
                    red
                  {% endif %}
                  ;
                }
          - entity: sensor.memory_use_percent
            name: Memory 
          - entity: sensor.swap_use_percent
            name: Swap
            icon: mdi:file-swap         
          - entity: sensor.disk_use_percent
            name: Disk 
          - entity: sensor.influxdb_database_size
            icon: mdi:database-outline
          - entity: sensor.mariadb_database_size
            icon: mdi:database  
          - entity: sensor.samba_backup
            icon: mdi:content-save-all      
      - type: entities
        entities:
          - entity: automation.batterie_benachrichtigung
          - type: custom:fold-entity-row
            head:
              type: section
              label: Einstellungen
            padding: 5
            entities:
              - entity: input_number.battery_alert
                name: Grenzwert
                tap_action: 
                  action: none
              - entity: script.battery_persistent_notification_clear
                name: Alarm zurücksetzen
                tap_action: 
                  action: toggle
  - title: FritzBox
    path: fritz
    icon: mdi:router-wireless-settings
    type: custom:horizontal-layout
    layout:
      max_cols: 2
    cards:
      - type: glance
        columns: 4
        show_name: false
        entities:
          - entity: sensor.net_download_max
            icon: mdi:cloud-download
          - entity: sensor.net_upload_max
            icon: mdi:cloud-upload
          - entity: sensor.fritz_box_7590_kb_s_received
            icon: mdi:cloud-download-outline
          - entity: sensor.fritz_box_7590_kb_s_sent
            icon: mdi:cloud-upload-outline
          - sensor.fritz_box_7590_connection_uptime
          - entity: sensor.wireguard_iphonepro
            icon: mdi:cellphone-iphone
          - entity: sensor.wireguard_ipad
            icon: mdi:tablet-ipad   
      - type: entities
        entities:
          - entity: switch.pi_hole
            icon: mdi:pi-hole    
          - entity: switch.fritz_box_7590_port_forward_http_server
            name: 'Fritz!Box Port: 80'
            tap_action: 
              action: toggle
          - entity: switch.fritz_box_7590_port_forward_https_server
            name: 'Fritz!Box Port: 443'
            tap_action: 
              action: toggle 
      - type: entities
        entities:
          - entity: switch.fritz_box_7590_wi_fi_google_messwagen_26
            name: 'Wi-Fi FRITZ!Box 2.4Ghz'
            tap_action: 
              action: toggle 
          - entity: switch.fritz_box_7590_wi_fi_google_messwagen_26_5ghz
            name: 'Wi-Fi FRITZ!Box 5Ghz'
            tap_action: 
              action: toggle 
          - entity: switch.fritz_box_7590_wi_fi_tanzergast
            name: 'Wi-Fi FRITZ!Box Gastzugang'
            tap_action: 
              action: toggle 
          - type: custom:auto-entities
            filter:
              include:
                - entity_id: "*internet_access"
            sort:
              method: name
            card:
              type: custom:fold-entity-row
              head:
                type: section
                label: Internet Zugang
              padding: 5