devices:
  f460f75e_a0abe852:
    name: iphonex_wolfgang
  9f73134d_730b488d:
    name: hp_spectre_chrome
  fa4c095e_b9eaf25f:
    name: ipad
  7b1395cf_7cb2985c:
    name: ipad_mini
  0413dbe9_e78fb23d:
    name: iphone_anita