devices:
  60441c8e_909dbeb0:
    name: iphonex_wolfgang
  9f73134d_730b488d:
    name: hp_spectre_chrome
  fa4c095e_b9eaf25f:
    name: ipad
  28e8825e_b3559962:
    name: ipad_mini
  0413dbe9_e78fb23d:
    name: iphone_anita