devices:
  f460f75e_a0abe852:
    name: iphonex_wolfgang
  9f73134d_730b488d:
    name: hp_spectre_chrome
  b3a7cb37_a516a1fe:
    name: ipad
  370dee15_311dc6aa:
    name: ipad_mini
  0413dbe9_e78fb23d:
    name: iphone_anita
  e5f7195e_1e5a637d:
    name: Arbeit Wolfgang