- platform: caldav
  username: !secret next_user
  password: !secret next_password
  url: !secret next_url
  custom_calendars:
    - name: 'Putzfrau'
      calendar: 'Privat'
      search: 'Putzfrau'
    - name: 'Urlaub'
      calendar: 'Privat'
      search: 'Urlaub'
    - name: 'BusinessTrip'
      calendar: 'Arbeit'
      search: 'Business Trip'