auto_start: False
filter:
  include_entities:
    - light.gateway_light_7811dcb258d1
    - light.sonoff_office
    - light.nachttischlampe_wolfgang
    - light.nachttischlampe_anita
    # - light.lights_kitchen
    - light.lights_living_room
    - climate.oeq1701003
    - climate.fritz_thermostat
    - climate.oeq1696358
    - climate.oeq1696369
    - climate.int0000002
    - script.1532173931522
    - script.1532175994947
    - light.steckdose_2
    - light.steckdose_4
    - media_player.bad
    - media_player.schlafzimmer
    - media_player.kuche
    - switch.radiator_on_off
    - switch.power_plug_printer
    - switch.power_plug_plug_3
    - sensor.temperature_158d0001b8c96c
    - sensor.temperature_158d0001b8c998
    - sensor.temperature_158d0002239fb5
    - sensor.temperature_158d00023258bd
    - sensor.humidity_158d0001b8c998
    - sensor.humidity_158d0002239fb5
    - sensor.humidity_158d00023258bd
    - sensor.humidity_158d0001b8c96c
    - sensor.oeq1667238_humidity
    - switch.tv_switch
    - switch.music_switch
    - switch.vacuum
    - switch.wifi_steckdose
    - switch.steckdose_1
entity_config:
    media_player.schlafzimmer:
      feature_list:
        - feature: play_pause
    media_player.bad:
      feature_list:
        - feature: play_pause
    media_player.kuche:
      feature_list:
        - feature: play_pause
    sensor.temperature_158d0001b8c96c:
      low_battery_threshold: 0
    sensor.temperature_158d0001b8c998:
      low_battery_threshold: 0
    sensor.temperature_158d0002239fb5:
      low_battery_threshold: 0
    sensor.temperature_158d00023258bd:
      low_battery_threshold: 0
    sensor.humidity_158d0001b8c998:
      low_battery_threshold: 0
    sensor.humidity_158d0002239fb5:
      low_battery_threshold: 0
    sensor.humidity_158d00023258bd:
      low_battery_threshold: 0
    sensor.oeq1667238_humidity:
      low_battery_threshold: 0
    sensor.humidity_158d0001b8c96c:
      low_battery_threshold: 0