camera_cctv:
    name: Kamera
    icon: mdi:cctv
    
automation_xiaomi_vacuum:
    name: Staubsaugerautomatisierung
    icon: mdi:home-assistant
    
automation_radiator:
    name: Heizungsautomatisierung (Temp)
    icon: mdi:home-assistant

radiator_on_off:
    name: heizungsstatus

persistent_notification:
    name: Benarichtigungen
    initial: off

car_map:
    name: Karte
    icon: mdi:map-legend

presence_map:
    name: Karte
    icon: mdi:map-legend

room_view:
    name: Raumansicht
    icon: mdi:home-circle-outline