purge_interval: 1
purge_keep_days: 1
# db_url: mysql://hass:securepw@core-mariadb/homeassistant?charset=utf8
exclude:
  domains:
    - group
    - device_tracker
    - sensor
    - light
    - media_player
    - scene
    - switch
    - camera
    - switch
    - binary_sensor
    - climate
    - calendar
    - input_number
    - camera
  entities:
    - sun.sun
    - automation.battery_persistent_notification
    - weather.dark_sky
    - automation.badge_zurucksetzen
    - counter.badge_counter
    - script.1570439203461
include:
  entities:
    - sensor.disk_free
    - sensor.memory_free
    - sensor.memory_free_2
    - sensor.processor_use
    - sensor.processor_use_2
    - sensor.cpu_temperature
    - sensor.memory_use
    - sensor.memory_use_2
    - sensor.memory_use_percent
    - sensor.memory_use_percent_2
    - sensor.disk_use
    - sensor.disk_use_percent
    - sensor.car_days_in_use
    - sensor.car_km_threshold
    - sensor.car_km_usage
    - sensor.humidity_158d0001b8c96c
    - sensor.humidity_158d0001b8c998
    - sensor.humidity_158d0002239fb5
    - sensor.humidity_158d00023258bd
    - sensor.oeq1667238_humidity
    - sensor.oeq1667238_temperature
    - sensor.temperature_158d0001b8c96c
    - sensor.temperature_158d0001b8c998
    - sensor.temperature_158d0002239fb5
    - sensor.temperature_158d00023258bd
    - sensor.hs110_today_kwh
    - sensor.hs110_volts
    - sensor.hs110_total_kwh
    - sensor.hs110_watts
    - sensor.hs110_amps