# lovelace_gen

# -----------------------------
title: Staubsauger

views:
  - title: Staubsauger
    path: vacuum
    icon: mdi:robot-vacuum
    type: custom:horizontal-layout
    layout:
      max_cols: 2
      width: 330
    cards:
      # - type: custom:vertical-stack-in-card
      #   cards:
          # - type: custom:vacuum-card
          #   entity: vacuum.roborock_vacuum
          #   style: |
          #     :host .toolbar {
          #       background: var( --ha-card-background, var(--card-background-color, white) );
          #       box-shadow: var( --ha-card-box-shadow, 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12) )
          #     }
          #   compact_view: true
          #   stats:
          #     default:
          #       - attribute: filter_left
          #         unit: Stunden
          #         subtitle: Filter
          #       - attribute: side_brush_left
          #         unit: Stunden
          #         subtitle: Seitenbürste
          #       - attribute: main_brush_left
          #         unit: Stunden
          #         subtitle: Hauptbürste
          #       - attribute: sensor_dirty_left
          #         unit: Stunden
          #         subtitle: Sensoren
          #     cleaning:
          #       - attribute: cleaned_area
          #         unit: m2
          #         subtitle: Bereich
          #       - attribute: cleaning_time
          #         unit: minutes
          #         subtitle: Dauer
      - type: entities
        entities:
          - entity: vacuum.roborock_vacuum
          - entity: automation.xiaomi_staubsauger_abwesenheit
            name: Saugen bei Abwesenheit
            icon: mdi:account-off
            tap_action: 
              action: toggle
          - type: custom:fold-entity-row
            head:
              type: section
              label: Einstellungen
            padding: 5
            entities:
              - entity: automation.xiaomi_staubsauger_neustart
                name: Neustarten (Bürste blockiert)
                icon: mdi:restart
                tap_action: 
                  action: toggle
              - entity: automation.xiaomi_staubsauger_error_stop
                name: Deaktivieren (b. Fehler)
                icon: mdi:restart-off
                tap_action: 
                  action: toggle
              - counter.xiaomo_errors
              - entity: script.xiaomi_vacuum_sensor_cleaned
                name: Sensor gereinigt
                tap_action: 
                  action: toggle
              - entity: script.xiaomi_vacuum_mainbrush_changed
                name: Hauptbürste gewechselt
                tap_action: 
                  action: toggle
              - entity: script.xiaomi_vacuum_sidebrush_changed
                name: Seitenbürst gewechselt
                tap_action: 
                  action: toggle
              - entity: script.xiaomi_vacuum_filter_changed
                name: Filter gereinigt
                tap_action: 
                  action: toggle
          - type: custom:fold-entity-row
            head:
              type: section
              label: Mitteilungen
            padding: 5
            entities:
              - entity: automation.xiaomi_staubsauger_fehler
                name: Fehler
                tap_action: 
                  action: toggle
              - entity: automation.xiaomi_staubsauger_fertig
                name: Reinigung abgeschlossen
                tap_action: 
                  action: toggle
              - entity: automation.xiaomi_staubsauger_gestartet
                name: Staubsauger gestartet
                tap_action: 
                  action: toggle
              - entity: automation.xiaomi_staubsauger_filter_kritisch
                name: Filter kritisch
                tap_action: 
                  action: toggle
              - entity: automation.xiaomi_staubsauger_sensor_kritisch
                name: Sensor kritisch
                tap_action: 
                  action: toggle 
          - type: custom:auto-entities
            filter:
              include:
                - entity_id: "sensor.rockrobo_vacuum_v1*"
            card:
              type: custom:fold-entity-row
              head:
                type: section
                label: Details
              padding: 5
  - title: Valetudo
    path: valetudo
    type: panel
    cards:
      - type: iframe
        url: http://192.168.200.29
        aspect_ratio: 100%