# lovelace_gen

title: Automations
path: automations
icon: mdi:calendar-multiple-check
type: custom:masonry-layout
layout:
  max_cols: 2
  height: auto
cards:
  - type: custom:scheduler-card
    include:
      - light
      - person.christina
      - person.wolfgang
      - scene
      - script
      - switch
      - vacuum
      - climate
      - media_player
      - button
    exclude:
      - media_player.airport_express
      - media_player.harman_kardon_avr
      - light.flur1
      - light.flur2
      - light.flur3
      - light.gruppe*
      - light.rwl021_23
      - switch.docker*
      - switch.*_internet_access
# '    time_step: 1
#     customize:
#       script.sonos_wecker:
#         actions:
#           - service: script.sonos_wecker
#             name: Weckton
#             icon: mdi:alarm
#             variables:
#               alarm_source:
#                 name: Quelle
#                 options:
#                   - value: 'Radio: BR24'
#                   - value: 'Radio: Superfly.fm'
#       person.wolfgang:
#         states:
#           - home
#           - not_home
#       person.christina:
#         states:
#           - home
#           - not_home'
    title: ''