# lovelace_gen

title: Automations
path: automations
icon: mdi:calendar-multiple-check
cards:
##################################################
  # - template: title
  #   type: 'custom:button-card'
  #   label: Scheduler 
  - type: custom:scheduler-card
    include:
      - light
      - person.christina
      - person.wolfgang
      - scene
      - script
      - switch
      - vacuum
      - climate
      - media_player
      - button
    exclude:
      - media_player.airport_express
      - media_player.harman_kardon_avr
      - light.flur1
      - light.flur2
      - light.flur3
      - light.gruppe*
      - light.rwl021_23
      - switch.docker*
      - switch.*_internet_access
    title: ''