# lovelace_gen

title: Automations
path: automations
icon: mdi:home-assistant
type: custom:horizontal-layout
layout:
  max_cols: 2
cards:
  - type: entities
    entities:
      - type: custom:template-entity-row
        icon: mdi:home-assistant
        name: Lichtsteuerung
        tap_action:
          action: none
      - type: section
      - entity: automation.licht_bewegung_kuche
        icon: mdi:motion-sensor
        name: Bewegungssensor Küche
        tap_action:
          action: toggle
        double_tap_action:
          action: navigate
          navigation_path: /config/automation/edit/1629968502070
      - entity: automation.licht_bewegung_flur
        icon: mdi:motion-sensor
        name: Bewegungssensor Flur
        tap_action:
          action: toggle
        double_tap_action:
          action: navigate
          navigation_path: /config/automation/edit/1629968323395
