# lovelace_gen

title: Automations
path: automations
icon: mdi:calendar-multiple-check
type: custom:masonry-layout
layout:
  max_cols: 2
  width: 330
cards:
  - type: custom:scheduler-card
    display_options:
      primary_info:
        - name
        - additional-tasks
      secondary_info: relative-time
    include:
      - light.gateway_light_7811dcb258d1
      - light.lights_bed_room
      - light.lights_kitchen
      - light.lights_living_room
      - light.nachttischlampe_wolfgang
      - light.wohnzimmer_couch
      - light.wohnzimmer_decke
      - light.wohnzimmer_wand
      - light.yeelight_bslamp1_0x0000000005451cd6
      - media_player.kuche
      - media_player.schlafzimmer
      - media_player.wohnzimmer
      - person.christina
      - person.wolfgang
      - scene.nachtlicht_hell
      - scene.schlafzimmer_gedimmt
      - scene.schlafzimmer_hell
      - scene.schlafzimmer_nachtlicht
      - scene.wohnzimmer_energie_tanken
      - scene.wohnzimmer_entspannen
      - scene.wohnzimmer_gedimmt
      - scene.wohnzimmer_hell
      - scene.wohnzimmer_konzentrieren
      - scene.wohnzimmer_lesen
      - scene.wohnzimmer_nachtlicht
      - script.harmony_power_off
      - script.sonos_b5_aktuell
      - script.sonos_superfly
      - script.sonos_wecker
      - switch
      - vacuum
      - climate
    time_step: 1
    customize:
      script.sonos_wecker:
        actions:
          - service: script.sonos_wecker
            name: Weckton
            icon: mdi:alarm
            variables:
              alarm_source:
                name: Quelle
                options:
                  - value: 'Radio: BR24'
                  - value: 'Radio: Superfly.fm'
      person.wolfgang:
        states:
          - home
          - not_home
      person.christina:
        states:
          - home
          - not_home
    title: false
  # - type: entities
  #   entities:
  #     - entity: automation.licht_bewegung_kuche
  #       type: custom:multiple-entity-row
  #       entities:
  #         - entity: sensor.bewegungsmelder
  #           name: Helligkeit
  #           format: precision0
  #         - entity: binary_sensor.bewegungsmelder
  #           name: Bewegung
  #       toggle: true
  #       icon: mdi:motion-sensor
  #       name: Küche
  #       tap_action:
  #         action: toggle
  #       double_tap_action:
  #         action: navigate
  #         navigation_path: /config/automation/edit/1629983354095
      # - entity: automation.licht_bewegung_flur
      #   type: custom:multiple-entity-row
      #   entities:
      #     - entity: sensor.illumination_7811dcb258d1
      #       name: Helligkeit
      #       format: precision0
      #     - entity: binary_sensor.tradfri_bewegungsmelder
      #       name: Bewegung
      #   toggle: true
      #   icon: mdi:motion-sensor
      #   name: Flur
      #   tap_action:
      #     action: toggle
      #   double_tap_action:
      #     action: navigate
      #     navigation_path: /config/automation/edit/1629983281720
      # - entity: automation.licht_bewegung_flur_nachtlicht
      #   type: custom:multiple-entity-row
      #   entities:
      #     - entity: sensor.illumination_7811dcb258d1
      #       name: Helligkeit
      #       format: precision0
      #     - entity: binary_sensor.tradfri_bewegungsmelder
      #       name: Bewegung
      #   toggle: true
      #   icon: mdi:motion-sensor
      #   name: Flur Nachtlicht
      #   tap_action:
      #     action: toggle
      #   double_tap_action:
      #     action: navigate
      #     navigation_path: /config/automation/edit/1634642436148
      # - type: weblink
      #   url: /config/automation/dashboard
      #   name: Automatisierungen
      #   icon: mdi:home-automation